package gamemode

import (
	"image/color"
	"time"
)

const (
	robrowserActiveEffectTableEntries = 607
	robrowserNumericEffectConstants   = 1147
)

func roBrowserEffectSize(value float64) float64 {
	return value * roBrowserEffectPixelRatio
}

var worldEffectSpecs = map[int]worldEffectSpec{
	effectBeginSpell:  castAuraEffectSpec("ring_yellow", color.RGBA{R: 255, G: 245, B: 120, A: 255}, 0.8, 4, 5),
	effectBeginSpell2: elementalCastAuraEffectSpec("ring_blue", color.RGBA{R: 128, G: 128, B: 255, A: 255}, 0.6),
	effectBeginSpell3: elementalCastAuraEffectSpec("ring_red", color.RGBA{R: 255, G: 100, B: 100, A: 255}, 0.7),
	effectBeginSpell4: elementalCastAuraEffectSpec("ring_white", color.RGBA{R: 150, G: 255, B: 150, A: 255}, 0.6),
	effectBeginSpell5: elementalCastAuraEffectSpec("ring_yellow", color.RGBA{R: 255, G: 245, B: 120, A: 255}, 0.8),
	effectBeginSpell6: castAuraEffectSpec("ring_white", color.RGBA{R: 255, G: 255, B: 255, A: 255}, 0.8, 4, 5),
	effectBeginSpell7: elementalCastAuraEffectSpec("ring_purple", color.RGBA{R: 200, G: 160, B: 255, A: 255}, 0.7),
	effectFirefly: {
		duration: 3 * time.Second,
		components: []worldEffectComponent{{
			kind:           effectComponent3D,
			spriteFile:     "data/sprite/\xC0\xCC\xC6\xD1\xC6\xAE/particle1",
			spriteRepeat:   true,
			duration:       3 * time.Second,
			duplicate:      3,
			duplicateDelay: 420 * time.Millisecond,
			posXRand:       0.18,
			posYRand:       0.18,
			posZ:           0.25,
			posZEnd:        1.0,
			posZStartRand:  0.2,
			posZEndRand:    0.25,
			sizeStart:      roBrowserEffectSize(70),
			sizeEnd:        roBrowserEffectSize(110),
			alphaMax:       0.22,
			fadeIn:         true,
			fadeOut:        true,
			color:          color.RGBA{R: 230, G: 250, B: 255, A: 255},
		}},
	},
	effectTorch: {
		duration: 24 * time.Hour,
		components: []worldEffectComponent{{
			kind:           effectComponent3D,
			spriteFile:     "torch_01",
			spriteRepeat:   true,
			duration:       600 * time.Millisecond,
			spriteDelay:    100 * time.Millisecond,
			posX:           0.1,
			posZ:           0.8,
			sizeStart:      roBrowserEffectSize(100),
			sizeEnd:        roBrowserEffectSize(100),
			angleStart:     270,
			angleEnd:       270,
			rotateToTarget: true,
			alphaMax:       1,
			color:          color.RGBA{R: 255, G: 255, B: 255, A: 255},
		}},
	},
	effectBubble: strEffectSpecRandom("bubble%d", "", 1, 4),
	effectPneuma: strEffectSpecRandom("pneuma%d", "", 1, 3),
	effectCastRing: {
		duration: 900 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:             effectComponentFUNC,
			funcAdapter:      effectFuncCastRing,
			funcName:         "CastRing",
			textureName:      "ring_yellow",
			duration:         900 * time.Millisecond,
			alphaMax:         0.9,
			fade:             true,
			rotate:           true,
			animation:        1,
			bottomSize:       0.8,
			topSize:          2.45,
			height:           2.8,
			posZ:             0.08,
			totalCircleSides: 20,
			circleSides:      20,
			color:            color.RGBA{R: 255, G: 245, B: 150, A: 255},
		}},
	},
	effectGroundSample: {
		duration: 900 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:        effectComponentFUNC,
			funcAdapter: effectFuncGroundSample,
			funcName:    "MagicTarget",
			textureFile: "effect/magic_target.tga",
			duration:    900 * time.Millisecond,
			alphaMax:    0.9,
			posZ:        0.08,
			sizeStart:   1,
			sizeEnd:     1,
		}},
	},
	effectBashHit: {
		duration:   350 * time.Millisecond,
		sfx:        []string{"effect\\ef_hit2.wav"},
		components: bashHitComponents(),
	},
	effectSafetyWall: {
		duration: 50 * time.Second,
		sfx:      []string{"effect\\ef_glasswall.wav"},
		components: []worldEffectComponent{
			{
				kind:    effectComponentSTR,
				strFile: "safetywall",
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.6,
				topSize:          0.6,
				height:           7,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				delay:            50 * time.Millisecond,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.65,
				topSize:          0.65,
				height:           6,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				delay:            100 * time.Millisecond,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.7,
				topSize:          0.7,
				height:           7,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
		},
	},
	effectMammonite: strEffectSpecAttachedMin("maemor", "memor_min", "effect\\ef_coin2.wav", false),
	effectSight: {
		duration: 12200 * time.Millisecond,
		sfx:      []string{"effect\\ef_sight.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentCylinder,
				textureName:      "ring_blue",
				duration:         900 * time.Millisecond,
				duplicateDelay:   800 * time.Millisecond,
				alphaMax:         0.5,
				fadeOut:          true,
				rotate:           true,
				bottomSize:       0.4,
				topSize:          1.8,
				height:           0.06,
				totalCircleSides: 3,
				circleSides:      3,
				color:            color.RGBA{R: 255, G: 210, B: 96, A: 255},
				duplicate:        10,
			},
			{
				kind:             effectComponent3D,
				spriteFile:       "sight",
				spriteRepeat:     true,
				duration:         12200 * time.Millisecond,
				duplicateDelay:   0,
				alphaMax:         123.0 / 255.0,
				posZ:             4,
				sizeStart:        60 * roBrowserEffectPixelRatio,
				sizeEnd:          80 * roBrowserEffectPixelRatio,
				angleStart:       0,
				angleEnd:         360,
				orbitRadiusX:     3,
				orbitRadiusY:     3,
				orbitRotations:   10,
				orbitPhase:       0.9,
				orbitPhaseDelta:  -0.1,
				orbitClockwise:   true,
				duplicate:        10,
				totalCircleSides: 10,
				color:            color.RGBA{R: 255, G: 220, B: 120, A: 255},
			},
		},
	},
	effectNapalmBeat: {
		duration: 700 * time.Millisecond,
		sfx:      []string{"effect\\ef_napalmbeat.wav"},
	},
	effectSoulStrike: {
		duration: 450 * time.Millisecond,
		sfx:      []string{"effect\\ef_soulstrike.wav"},
		components: []worldEffectComponent{
			{
				kind:            effectComponent3D,
				color:           color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile:     "effect/pok3.tga",
				duration:        200 * time.Millisecond,
				delay:           250 * time.Millisecond,
				duplicateDelay:  150 * time.Millisecond,
				toSrc:           true,
				alphaMax:        1,
				fadeIn:          true,
				fadeOut:         true,
				posZEnd:         1,
				posZStartRand:   5,
				posZStartMiddle: 6,
				posZSmooth:      true,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:           effectComponent3D,
				spriteFile:     "data/sprite/\xC0\xCC\xC6\xD1\xC6\xAE/particle1",
				spriteRepeat:   true,
				duration:       250 * time.Millisecond,
				duplicate:      5,
				duplicateDelay: 20 * time.Millisecond,
				toSrc:          true,
				rotateToTarget: true,
				arc:            4,
				retreat:        3,
				posZ:           3,
				sizeStart:      100 * roBrowserEffectPixelRatio,
				sizeEnd:        roBrowserEffectSize(500),
			},
		},
	},
	effectEndure: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_endure.wav"},
		components: []worldEffectComponent{{
			kind:        effectComponent3D,
			textureFile: "effect/endure.tga",
			duration:    1000 * time.Millisecond,
			alphaMax:    1,
			fadeIn:      true,
			fadeOut:     true,
			posZ:        2,
			sizeStart:   200 * roBrowserEffectPixelRatio,
			sizeEnd:     70 * roBrowserEffectPixelRatio,
			sizeSmooth:  true,
		}},
	},
	effectBashBegin: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_bash.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_down",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.1,
				topSize:          2.0,
				posZ:             1.5,
				totalCircleSides: 20,
				circleSides:      20,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_center",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.01,
				topSize:          2.5,
				posZ:             1.5,
				totalCircleSides: 30,
				circleSides:      1,
				duplicate:        10,
				angleZRandom:     360,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "alpha_center",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.01,
				topSize:          4.0,
				posZ:             1.5,
				totalCircleSides: 30,
				circleSides:      1,
				duplicate:        8,
				angleZRandom:     360,
			},
		},
	},
	effectProvoke: {
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\swordman_provoke.wav"},
		components: []worldEffectComponent{{
			kind:    effectComponentSTR,
			color:   color.RGBA{R: 255, G: 70, B: 42, A: 255},
			strFile: "provoke",
		}},
	},
	effectMagnumBreak: {
		duration: 300 * time.Millisecond,
		sfx:      []string{"effect\\ef_magnumbreak.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentCylinder,
				textureName:      "ring_yellow",
				duration:         300 * time.Millisecond,
				alphaMax:         0.7,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       4,
				topSize:          6,
				height:           1,
				totalCircleSides: 32,
				circleSides:      32,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "\xb4\xeb\xc6\xf8\xb9\xdf",
				duration:         300 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       4,
				topSize:          1,
				height:           4,
				totalCircleSides: 32,
				circleSides:      32,
			},
		},
	},
	effectQuakeMagnum: {
		duration:    50 * time.Millisecond,
		cameraShake: 50 * time.Millisecond,
	},
	effectSteal: {
		duration: 500 * time.Millisecond,
		sfx:      []string{"effect\\ef_steal.wav"},
		components: []worldEffectComponent{{
			kind:          effectComponent3D,
			color:         color.RGBA{R: 255, G: 255, B: 216, A: 255},
			textureFile:   "effect/pok1.tga",
			duration:      500 * time.Millisecond,
			alphaMax:      1,
			fadeOut:       true,
			posXEndRand:   3.5,
			posYEndRand:   3.5,
			posZEndRand:   1,
			posZEndMiddle: 3,
			sizeStart:     200 * roBrowserEffectPixelRatio,
			sizeEnd:       10 * roBrowserEffectPixelRatio,
			duplicate:     7,
		}},
	},
	effectPoisonAttack: {
		duration: 2800 * time.Millisecond,
		sfx:      []string{"effect\\ef_detoxication.wav"},
		components: []worldEffectComponent{{
			kind:           effectComponent3D,
			color:          color.RGBA{R: 255, G: 178, B: 255, A: 255},
			textureFile:    "effect/pok1.tga",
			duration:       1000 * time.Millisecond,
			alphaMax:       1,
			fadeIn:         true,
			fadeOut:        true,
			posXRand:       1,
			posYRand:       1,
			posZEnd:        5,
			sizeStart:      100 * roBrowserEffectPixelRatio,
			sizeEnd:        100 * roBrowserEffectPixelRatio,
			sizeRand:       20 * roBrowserEffectPixelRatio,
			duplicate:      10,
			duplicateDelay: 200 * time.Millisecond,
		}},
	},
	effectDetoxication: {
		duration: 2800 * time.Millisecond,
		sfx:      []string{"effect\\ef_detoxication.wav"},
		components: []worldEffectComponent{{
			kind:           effectComponent3D,
			color:          color.RGBA{R: 178, G: 255, B: 255, A: 255},
			textureFile:    "effect/pok1.tga",
			duration:       1000 * time.Millisecond,
			alphaMax:       1,
			fadeIn:         true,
			fadeOut:        true,
			posXRand:       1,
			posYRand:       1,
			posZEnd:        5,
			sizeStart:      100 * roBrowserEffectPixelRatio,
			sizeEnd:        100 * roBrowserEffectPixelRatio,
			sizeRand:       20 * roBrowserEffectPixelRatio,
			duplicate:      10,
			duplicateDelay: 200 * time.Millisecond,
		}},
	},
	effectStoneCurse: strEffectSpecAttached("stonecurse", "", false),
	effectColdBolt: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_icearrow1.wav", "effect\\ef_icearrow2.wav", "effect\\ef_icearrow3.wav"},
		components: []worldEffectComponent{
			{
				kind:            effectComponent3D,
				textureFile:     "effect/icearrow.tga",
				duration:        500 * time.Millisecond,
				alphaMax:        1,
				posXStartMiddle: 5,
				posXStartRand:   1,
				posYStartMiddle: 2,
				posYStartRand:   1,
				posZ:            20,
				posXEnd:         0.0001,
				posYEnd:         0.0001,
				posZEnd:         0.0001,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
				angleStart:      112.5,
				angleEnd:        112.5,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      "ring_blue",
				duration:         1000 * time.Millisecond,
				delay:            500 * time.Millisecond,
				alphaMax:         0.7,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       3,
				topSize:          5,
				height:           0.1,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 170, B: 255, A: 255},
			},
		},
	},
	effectFireBolt: {
		duration: 500 * time.Millisecond,
		sfx:      []string{"effect\\ef_firearrow1.wav", "effect\\ef_firearrow2.wav", "effect\\ef_firearrow3.wav"},
		components: []worldEffectComponent{{
			kind: effectComponent3D,
			textureFiles: []string{
				"effect/\xba\xd2\xc8\xad\xbb\xec1.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec2.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec3.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec4.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec5.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec6.tga",
			},
			duration:        500 * time.Millisecond,
			alphaMax:        1,
			blendAdditive:   true,
			posXStartMiddle: 5,
			posXStartRand:   1,
			posYStartMiddle: 2,
			posYStartRand:   1,
			posZ:            20,
			posXEnd:         0.0001,
			posYEnd:         0.0001,
			posZEnd:         0.0001,
			sizeStartX:      100 * roBrowserEffectPixelRatio,
			sizeEndX:        100 * roBrowserEffectPixelRatio,
			sizeStartY:      50 * roBrowserEffectPixelRatio,
			sizeEndY:        50 * roBrowserEffectPixelRatio,
			angleStart:      112.5,
			angleEnd:        112.5,
		}},
	},
	effectFireBall: {
		duration: 410 * time.Millisecond,
		sfx:      []string{"effect\\ef_fireball.wav"},
		components: []worldEffectComponent{{
			kind:             effectComponent3D,
			spriteFile:       "fireball",
			spriteRepeat:     true,
			toSrc:            true,
			rotateToTarget:   true,
			duration:         250 * time.Millisecond,
			delay:            160 * time.Millisecond,
			alphaMax:         0.2,
			alphaMaxDelta:    0.2,
			rotateWithCamera: true,
			posZ:             2,
			sizeStart:        200 * roBrowserEffectPixelRatio,
			sizeEnd:          200 * roBrowserEffectPixelRatio,
			duplicate:        5,
		}},
	},
	effectFireWall: strEffectSpecRandom("firewall%d", "effect\\ef_firewall.wav", 1, 2),
	effectFrostDiver: {
		duration: 450 * time.Millisecond,
		sfx:      []string{"effect\\ef_frostdiver.wav"},
		components: []worldEffectComponent{{
			kind:        effectComponent3D,
			textureFile: "effect/ice.tga",
			duration:    450 * time.Millisecond,
			toSrc:       true,
			alphaMax:    0.75,
			fadeOut:     true,
			posZ:        0.7,
			posZEnd:     0.9,
			sizeStart:   90 * roBrowserEffectPixelRatio,
			sizeEnd:     130 * roBrowserEffectPixelRatio,
			angleStart:  0,
			angleEnd:    -180,
		}},
	},
	effectFrostDiverHit: strEffectSpecAttached("freeze", "effect\\ef_frostdiver2.wav", false),
	effectLightningBolt: {
		components: []worldEffectComponent{
			{
				kind:           effectComponentSTR,
				strFile:        "lightning",
				attachedEntity: true,
			},
			{
				kind:           effectComponentSTR,
				strFile:        "windhit%d",
				strRandMin:     1,
				strRandMax:     3,
				attachedEntity: true,
			},
		},
	},
	effectThunderStorm: strEffectSpec("thunderstorm", "effect\\magician_thunderstorm.wav"),
	effectRuwach: {
		duration: 12200 * time.Millisecond,
		sfx:      []string{"effect\\ef_ruwach.wav"},
		components: []worldEffectComponent{
			{
				kind:            effectComponent3D,
				spriteFile:      "data\\sprite\\shadow",
				shadowTexture:   true,
				duration:        12200 * time.Millisecond,
				alphaMax:        0.5,
				posX:            -2,
				sizeStart:       roBrowserEffectSize(0.4),
				sizeEnd:         roBrowserEffectSize(0.4),
				sizeDelta:       0.15,
				duplicate:       8,
				orbitRadiusX:    3,
				orbitRadiusY:    3,
				orbitRotations:  8,
				orbitPhase:      0.7,
				orbitPhaseDelta: -0.1,
				orbitClockwise:  true,
			},
			{
				kind:            effectComponent3D,
				color:           color.RGBA{G: 255, B: 255, A: 255},
				spriteFile:      "particle2",
				duration:        12200 * time.Millisecond,
				alphaMax:        0.07,
				alphaMaxDelta:   0.07,
				blendAdditive:   true,
				posX:            -2,
				posZ:            2,
				sizeStart:       roBrowserEffectSize(80),
				sizeEnd:         roBrowserEffectSize(80),
				sizeDelta:       30,
				duplicate:       10,
				orbitRadiusX:    3,
				orbitRadiusY:    3,
				orbitRotations:  8,
				orbitPhase:      0.7,
				orbitPhaseDelta: -0.1,
				orbitClockwise:  true,
			},
		},
	},
	effectIncAgility: {
		duration: 1500 * time.Millisecond,
		sfx:      []string{"effect\\ef_incagility.wav"},
		components: []worldEffectComponent{
			incAgilityParticleComponent(1, 500*time.Millisecond, 7),
			incAgilityParticleComponent(0.75, 400*time.Millisecond, 3),
			incAgilityParticleComponent(1, 0, 10),
			{
				kind:        effectComponent3D,
				color:       color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile: "effect/agi_up.bmp",
				duration:    1000 * time.Millisecond,
				alphaMax:    1,
				fadeIn:      true,
				fadeOut:     true,
				posZ:        0.4,
				posZEnd:     3,
				sizeStart:   100 * roBrowserEffectPixelRatio,
				sizeEnd:     100 * roBrowserEffectPixelRatio,
				sizeStartY:  45 * roBrowserEffectPixelRatio,
				sizeEndY:    45 * roBrowserEffectPixelRatio,
				sizeSmooth:  true,
				overlay:     true,
			},
		},
	},
	effectDecAgility: {
		duration: 4800 * time.Millisecond,
		sfx:      []string{"effect\\ef_decagility.wav"},
		components: []worldEffectComponent{
			decAgilityParticleComponent(),
			{
				kind:        effectComponent3D,
				textureFile: "effect/slow.bmp",
				duration:    1000 * time.Millisecond,
				alphaMax:    1,
				fadeIn:      true,
				fadeOut:     true,
				posZ:        2.8,
				posZEnd:     0.4,
				sizeStart:   roBrowserEffectSize(100),
				sizeEnd:     roBrowserEffectSize(100),
				sizeStartY:  roBrowserEffectSize(45),
				sizeEndY:    roBrowserEffectSize(45),
				sizeSmooth:  true,
			},
		},
	},
	effectAqua: {
		sfx: []string{"effect\\ef_aqua.wav"},
		components: []worldEffectComponent{{
			kind:             effectComponentSPR,
			spriteFile:       "\xBC\xBA\xBC\xF6\xB6\xDF\xB1\xE2",
			spriteHead:       true,
			worldSizedSprite: true,
		}},
	},
	effectSignum:  strEffectSpecAttached("cross", "effect\\ef_signum.wav", false),
	effectAngelus: strEffectSpecAttachedMin("angelus", "jong_mini", "effect\\ef_angelus.wav", true),
	effectBlessing: {
		duration: 2500 * time.Millisecond,
		sfx:      []string{"effect\\ef_blessing.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentSPR,
				spriteFile:       "\xC3\xE0\xBA\xB9",
				duration:         1500 * time.Millisecond,
				spriteDelay:      30 * time.Millisecond,
				spriteRepeat:     true,
				spriteHead:       true,
				spriteYOffset:    -120,
				worldSizedSprite: true,
			},
			{
				kind:            effectComponent3D,
				spriteFile:      "particle6",
				duration:        1200 * time.Millisecond,
				delay:           300 * time.Millisecond,
				duplicate:       6,
				duplicateDelay:  0,
				alphaMax:        1,
				sparkling:       true,
				sparkNumber:     2,
				fadeIn:          true,
				fadeOut:         true,
				posXRand:        1.2,
				posYRand:        1,
				posZStartRand:   2,
				posZStartMiddle: 5.5,
				posZEndRand:     0.5,
				posZEndMiddle:   1,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:            effectComponent3D,
				spriteFile:      "particle6",
				duration:        1200 * time.Millisecond,
				delay:           400 * time.Millisecond,
				duplicate:       6,
				duplicateDelay:  0,
				alphaMax:        1,
				fadeIn:          true,
				fadeOut:         true,
				posXRand:        1.4,
				posYRand:        1.1,
				posZStartRand:   2,
				posZStartMiddle: 5.5,
				posZEndRand:     0.5,
				posZEndMiddle:   1,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:          effectComponent3D,
				color:         color.RGBA{R: 25, G: 191, B: 255, A: 255},
				textureFile:   "effect/pok2.tga",
				duration:      2500 * time.Millisecond,
				alphaMax:      0.3,
				fadeIn:        true,
				fadeOut:       true,
				sizeStart:     140 * roBrowserEffectPixelRatio,
				sizeEnd:       140 * roBrowserEffectPixelRatio,
				blendAdditive: true,
			},
		},
	},
	effectFireHit: strEffectSpecRandomAttached("firehit%d", "effect\\ef_firehit.wav", 1, 3, true, false),
	effectFireSplashHit: {
		duration: 500 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:        effectComponent2D,
			textureFile: "effect/firering.tga",
			duration:    500 * time.Millisecond,
			fadeOut:     true,
			posZ:        1,
			sizeStart:   10 * roBrowserEffectPixelRatio,
			sizeEnd:     300 * roBrowserEffectPixelRatio,
			angleStart:  0,
			angleEnd:    -360,
		}},
	},
	effectColdHit:       soundOnlyEffectSpec("_hit_fist3.wav", "_hit_fist4.wav"),
	effectWindHit:       strEffectSpecRandom("windhit%d", "", 1, 3),
	effectCure:          strEffectSpecAttachedMin("cure", "cure_min", "effect\\acolyte_cure.wav", false),
	effectConcentration: strEffectSpecAttached("concentration", "effect\\ac_concentration.wav", false),
	effectRefineOK:      strEffectSpecAttached("bs_refinesuccess", "effect\\bs_refinesuccess.wav", false),
	effectRefineFail:    strEffectSpecAttached("bs_refinefailed", "effect\\bs_refinefailed.wav", false),
	effectEnergyCoat:    strEffectSpecAttached("energycoat", "", false),
	effectTeleportation: {
		duration:         1500 * time.Millisecond,
		detachLocalActor: true,
		sfx:              []string{"effect\\ef_teleportation.wav"},
		components: []worldEffectComponent{
			teleportCylinderComponent(0.3, 0.3, 35),
			teleportCylinderComponent(0.6, 0.8, 25),
			teleportCylinderComponent(0.8, 1.0, 13),
			teleportCylinderComponent(1.0, 1.3, 5),
		},
	},
	effectPortal: {
		duration: 25000 * time.Millisecond,
		sfx:      []string{"effect\\ef_readyportal.wav", "effect\\ef_portal.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentCylinder,
				color:            color.RGBA{R: 153, G: 153, B: 255, A: 255},
				textureName:      "ring_blue",
				duration:         500 * time.Millisecond,
				alphaMax:         0.4,
				fadeOut:          true,
				rotate:           true,
				animation:        4,
				bottomSize:       2.4,
				topSize:          3.9,
				height:           0.1,
				posZ:             0.1,
				totalCircleSides: 32,
				circleSides:      32,
				blendAdditive:    true,
			},
			portalCylinderComponent(0.6, 0.6, 15, 0, "ring_blue", 0.3),
			portalCylinderComponent(0.8, 0.8, 13, 0, "ring_blue", 0.3),
			{
				kind:             effectComponentCylinder,
				color:            color.RGBA{R: 153, G: 153, B: 255, A: 255},
				textureName:      "alpha1",
				duration:         25000 * time.Millisecond,
				alphaMax:         0.5,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       1,
				topSize:          1,
				height:           1,
				posZ:             2,
				totalCircleSides: 20,
				circleSides:      10,
				blendAdditive:    true,
			},
		},
	},
	effectPharmacyOK:   strEffectSpecAttached("p_success", "effect\\p_success.wav", false),
	effectPharmacyFail: strEffectSpecAttached("p_failed", "effect\\p_failed.wav", false),
	effectHeal: {
		duration: 1840 * time.Millisecond,
		sfx:      []string{"_heal_effect.wav"},
		components: []worldEffectComponent{
			healCylinderComponent(0.95, 0.95, 8),
			healCylinderComponent(1.0, 1.0, 8),
			healParticleComponent(0.6, 1300*time.Millisecond, 400*time.Millisecond, 10*time.Millisecond, 15, 1.5, 1.5, 0, 0, 0, 2, 6, false),
			healParticleComponent(0.6, 1100*time.Millisecond, 200*time.Millisecond, 50*time.Millisecond, 7, 1, 1, 1, 0, 5, 0, 0, false),
		},
	},
	effectHealOffensive: {
		duration: 1490 * time.Millisecond,
		sfx:      []string{"_heal_effect.wav"},
		components: []worldEffectComponent{
			healOffensiveCylinderComponent(0.95, 0.95, 10),
			healOffensiveCylinderComponent(1.0, 1.0, 9),
			healParticleComponent(0.8, 1000*time.Millisecond, 400*time.Millisecond, 10*time.Millisecond, 10, 1.5, 1.5, 0, 0, 0, 3, 6, true),
			healParticleComponent(0.8, 900*time.Millisecond, 200*time.Millisecond, 50*time.Millisecond, 5, 1, 1, 1, 0, 6, 0, 0, true),
		},
	},
	effectBaseLevelUp: {
		duration: 1300 * time.Millisecond,
		sfx:      []string{"levelup.wav"},
		components: []worldEffectComponent{{
			kind:    effectComponentSTR,
			strFile: "angel",
		}},
	},
	effectJobLevelUp: {
		components: []worldEffectComponent{{
			kind:           effectComponentSTR,
			strFile:        "joblvup",
			attachedEntity: true,
		}},
	},
	effectPotionRed:    potionEffectSpec("\xbb\xa1\xb0\xa3\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 82, B: 70, A: 255}),
	effectPotionOrange: potionEffectSpec("\xc1\xd6\xc8\xab\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 145, B: 58, A: 255}),
	effectPotionYellow: potionEffectSpec("\xb3\xeb\xb6\xf5\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 226, B: 76, A: 255}),
	effectPotionWhite:  potionEffectSpec("\xc7\xcf\xbe\xe1\xc6\xf7\xbc\xc7", color.RGBA{R: 245, G: 245, B: 255, A: 255}),
	effectPotionBlue:   bluePotionEffectSpec(),
	effectPotionGreen:  potionEffectSpec("\xc3\xca\xb7\xcf\xc6\xf7\xbc\xc7", color.RGBA{R: 78, G: 225, B: 98, A: 255}),
	effectFood: {
		duration: 850 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:    effectComponentSTR,
			color:   color.RGBA{R: 255, G: 182, B: 86, A: 255},
			strFile: "fruit",
		}},
	},
	effectFoodBlue: {
		duration: 850 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:    effectComponentSTR,
			color:   color.RGBA{R: 132, G: 112, B: 255, A: 255},
			strFile: "fruit",
		}},
	},
}

func bashHitComponents() []worldEffectComponent {
	angleRanges := [][2]float64{
		{0, 35},
		{50, 85},
		{100, 135},
		{150, 185},
		{200, 235},
		{255, 290},
		{300, 335},
		{340, 360},
	}
	components := make([]worldEffectComponent, 0, len(angleRanges))
	for index, angleRange := range angleRanges {
		textureFile := "effect/lens1.tga"
		if index%2 == 1 {
			textureFile = "effect/lens2.tga"
		}
		components = append(components, worldEffectComponent{
			kind:               effectComponent2D,
			textureFile:        textureFile,
			duration:           250 * time.Millisecond,
			durationRandMin:    200 * time.Millisecond,
			durationRandMax:    350 * time.Millisecond,
			alphaMax:           12,
			fade:               true,
			fadeOut:            true,
			sizeStartXRandMin:  25 * roBrowserEffectPixelRatio,
			sizeStartXRandMax:  40 * roBrowserEffectPixelRatio,
			sizeStartY:         10 * roBrowserEffectPixelRatio,
			sizeEndX:           1 * roBrowserEffectPixelRatio,
			sizeEndYRandMin:    250 * roBrowserEffectPixelRatio,
			sizeEndYRandMax:    300 * roBrowserEffectPixelRatio,
			angleRandMin:       angleRange[0],
			angleRandMax:       angleRange[1],
			circlePattern:      true,
			circleInnerSize:    2.2,
			circleOuterRandMin: 5,
			circleOuterRandMax: 6,
			overlay:            true,
		})
	}
	return components
}

type effectCoverage struct {
	Implemented     int
	RobrowserActive int
	RobrowserAll    int
	ActivePercent   float64
	AllPercent      float64
}

func effectCoverageSnapshot() effectCoverage {
	implemented := len(worldEffectSpecs)
	return effectCoverage{
		Implemented:     implemented,
		RobrowserActive: robrowserActiveEffectTableEntries,
		RobrowserAll:    robrowserNumericEffectConstants,
		ActivePercent:   float64(implemented) / float64(robrowserActiveEffectTableEntries) * 100,
		AllPercent:      float64(implemented) / float64(robrowserNumericEffectConstants) * 100,
	}
}

func castAuraEffectSpec(texture string, tint color.RGBA, alphaMax, height, topSize float64) worldEffectSpec {
	return worldEffectSpec{
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\ef_beginspell.wav"},
		components: []worldEffectComponent{{
			kind:             effectComponentCylinder,
			textureName:      texture,
			duration:         900 * time.Millisecond,
			alphaMax:         alphaMax,
			fade:             true,
			rotate:           true,
			animation:        2,
			bottomSize:       1,
			topSize:          topSize,
			height:           height,
			totalCircleSides: 32,
			circleSides:      32,
			color:            tint,
		}},
	}
}

func elementalCastAuraEffectSpec(texture string, tint color.RGBA, alphaMax float64) worldEffectSpec {
	return worldEffectSpec{
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\ef_beginspell.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectComponentCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         0.3,
				fade:             true,
				rotate:           true,
				animation:        1,
				bottomSize:       1,
				topSize:          1,
				height:           30,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         alphaMax,
				fade:             true,
				rotate:           true,
				animation:        1,
				bottomSize:       1,
				topSize:          1.3,
				height:           2,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
			{
				kind:             effectComponentCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         alphaMax,
				fade:             true,
				rotate:           true,
				animation:        2,
				bottomSize:       1,
				topSize:          4,
				height:           3,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
		},
	}
}

func bluePotionEffectSpec() worldEffectSpec {
	spec := potionEffectSpec("\xc6\xc4\xb6\xf5\xc6\xf7\xbc\xc7", color.RGBA{R: 92, G: 150, B: 255, A: 255})
	spec.sfx = []string{"effect\\\xc8\xed\xb1\xe2.wav"}
	return spec
}

func incAgilityParticleComponent(alpha float64, delay time.Duration, duplicate int) worldEffectComponent {
	return worldEffectComponent{
		kind:            effectComponent3D,
		color:           color.RGBA{R: 255, G: 255, B: 255, A: 255},
		textureFile:     "effect/ac_center2.tga",
		duration:        1000 * time.Millisecond,
		delay:           delay,
		duplicateDelay:  200 * time.Millisecond,
		alphaMax:        alpha,
		fadeOut:         true,
		posXRand:        1.5,
		posYRand:        1,
		posZStartRand:   1,
		posZStartMiddle: 1,
		posZEndRand:     1,
		posZEndMiddle:   6,
		sizeStartX:      2.5 * roBrowserEffectPixelRatio,
		sizeEndX:        2.5 * roBrowserEffectPixelRatio,
		sizeRandY:       15 * roBrowserEffectPixelRatio,
		sizeRandYMiddle: 45 * roBrowserEffectPixelRatio,
		duplicate:       duplicate,
	}
}

func decAgilityParticleComponent() worldEffectComponent {
	return worldEffectComponent{
		kind:            effectComponent3D,
		textureFile:     "effect/ac_center2.tga",
		duration:        1000 * time.Millisecond,
		duplicateDelay:  200 * time.Millisecond,
		alphaMax:        1,
		fadeOut:         true,
		posXRand:        1.5,
		posYRand:        1,
		posZStartRand:   1,
		posZStartMiddle: 6,
		posZEndRand:     1,
		posZEndMiddle:   1,
		sizeStartX:      roBrowserEffectSize(2.5),
		sizeEndX:        roBrowserEffectSize(2.5),
		sizeRandY:       roBrowserEffectSize(15),
		sizeRandYMiddle: roBrowserEffectSize(45),
		duplicate:       20,
	}
}
