package gamemode

import (
	"image/color"
	"time"
)

const (
	robrowserActiveEffectTableEntries = 607
	robrowserNumericEffectConstants   = 1147
)

func roBrowserEffectSize(value float64) float64 {
	return value * roBrowserEffectPixelRatio
}

var worldEffectSpecs = map[int]worldEffectSpec{
	effectBeginSpell:  castAuraEffectSpec("ring_yellow", color.RGBA{R: 255, G: 245, B: 120, A: 255}, 0.8, 4, 5),
	effectBeginSpell2: elementalCastAuraEffectSpec("ring_blue", color.RGBA{R: 128, G: 128, B: 255, A: 255}, 0.6),
	effectBeginSpell3: elementalCastAuraEffectSpec("ring_red", color.RGBA{R: 255, G: 100, B: 100, A: 255}, 0.7),
	effectBeginSpell4: elementalCastAuraEffectSpec("ring_white", color.RGBA{R: 150, G: 255, B: 150, A: 255}, 0.6),
	effectBeginSpell5: elementalCastAuraEffectSpec("ring_yellow", color.RGBA{R: 255, G: 245, B: 120, A: 255}, 0.8),
	effectBeginSpell6: castAuraEffectSpec("ring_white", color.RGBA{R: 255, G: 255, B: 255, A: 255}, 0.8, 4, 5),
	effectBeginSpell7: elementalCastAuraEffectSpec("ring_purple", color.RGBA{R: 200, G: 160, B: 255, A: 255}, 0.7),
	effectFirefly: {
		duration: 3 * time.Second,
		components: []worldEffectComponent{{
			kind:           effectPrimitive3D,
			spriteFile:     "data/sprite/\xC0\xCC\xC6\xD1\xC6\xAE/particle1",
			spriteRepeat:   true,
			duration:       3 * time.Second,
			duplicate:      3,
			duplicateDelay: 420 * time.Millisecond,
			posXRand:       0.18,
			posYRand:       0.18,
			posZ:           0.25,
			posZEnd:        1.0,
			posZStartRand:  0.2,
			posZEndRand:    0.25,
			sizeStart:      roBrowserEffectSize(70),
			sizeEnd:        roBrowserEffectSize(110),
			alphaMax:       0.22,
			fadeIn:         true,
			fadeOut:        true,
			color:          color.RGBA{R: 230, G: 250, B: 255, A: 255},
		}},
	},
	effectTorch: {
		duration: 24 * time.Hour,
		components: []worldEffectComponent{{
			kind:           effectPrimitive3D,
			spriteFile:     "torch_01",
			spriteRepeat:   true,
			duration:       600 * time.Millisecond,
			spriteDelay:    100 * time.Millisecond,
			posX:           0.1,
			posZ:           0.8,
			sizeStart:      roBrowserEffectSize(100),
			sizeEnd:        roBrowserEffectSize(100),
			angleStart:     270,
			angleEnd:       270,
			rotateToTarget: true,
			alphaMax:       1,
			color:          color.RGBA{R: 255, G: 255, B: 255, A: 255},
		}},
	},
	effectBubble: strEffectSpecRandom("bubble%d", "", 1, 4),
	effectCastRing: {
		duration: 900 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:             effectPrimitiveCastRing,
			textureName:      "ring_yellow",
			duration:         900 * time.Millisecond,
			alphaMax:         0.9,
			fade:             true,
			rotate:           true,
			animation:        1,
			bottomSize:       0.8,
			topSize:          2.45,
			height:           2.8,
			posZ:             0.08,
			totalCircleSides: 20,
			circleSides:      20,
			color:            color.RGBA{R: 255, G: 245, B: 150, A: 255},
		}},
	},
	effectMagicTarget: {
		duration: 900 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:        effectPrimitiveGroundPlane,
			textureFile: "effect/magic_target.tga",
			duration:    900 * time.Millisecond,
			alphaMax:    0.9,
			posZ:        0.08,
			sizeStart:   1,
			sizeEnd:     1,
		}},
	},
	effectBashHit: {
		duration: 280 * time.Millisecond,
		sfx:      []string{"effect\\ef_hit2.wav"},
		components: []worldEffectComponent{{
			kind:  effectPrimitiveBashHit,
			color: color.RGBA{R: 255, G: 248, B: 220, A: 255},
		}},
	},
	effectSafetyWall: {
		duration: 50 * time.Second,
		sfx:      []string{"effect\\ef_glasswall.wav"},
		components: []worldEffectComponent{
			{
				kind:    effectPrimitiveSTR,
				strFile: "safetywall",
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.6,
				topSize:          0.6,
				height:           7,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				delay:            50 * time.Millisecond,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.65,
				topSize:          0.65,
				height:           6,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_down",
				duration:         50 * time.Second,
				delay:            100 * time.Millisecond,
				alphaMax:         0.4,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       0.7,
				topSize:          0.7,
				height:           7,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 25, B: 128, A: 255},
			},
		},
	},
	effectMammonite: strEffectSpec("maemor", "effect\\ef_coin2.wav"),
	effectSight: {
		duration: 12200 * time.Millisecond,
		sfx:      []string{"effect\\ef_sight.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "ring_blue",
				duration:         900 * time.Millisecond,
				duplicateDelay:   800 * time.Millisecond,
				alphaMax:         0.5,
				fadeOut:          true,
				rotate:           true,
				bottomSize:       0.4,
				topSize:          1.8,
				height:           0.06,
				totalCircleSides: 3,
				circleSides:      3,
				color:            color.RGBA{R: 255, G: 210, B: 96, A: 255},
				duplicate:        10,
			},
			{
				kind:             effectPrimitive3D,
				spriteFile:       "sight",
				spriteRepeat:     true,
				duration:         12200 * time.Millisecond,
				duplicateDelay:   120 * time.Millisecond,
				alphaMax:         123.0 / 255.0,
				posX:             -2,
				posY:             4,
				posZ:             4,
				sizeStart:        60 * roBrowserEffectPixelRatio,
				sizeEnd:          80 * roBrowserEffectPixelRatio,
				angleStart:       0,
				angleEnd:         360,
				duplicate:        10,
				totalCircleSides: 10,
				color:            color.RGBA{R: 255, G: 220, B: 120, A: 255},
			},
		},
	},
	effectSoulStrike: {
		duration: 450 * time.Millisecond,
		sfx:      []string{"effect\\ef_soulstrike.wav"},
		components: []worldEffectComponent{
			{
				kind:            effectPrimitive3D,
				color:           color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile:     "effect/pok3.tga",
				duration:        200 * time.Millisecond,
				delay:           250 * time.Millisecond,
				duplicateDelay:  150 * time.Millisecond,
				toSrc:           true,
				alphaMax:        1,
				fadeIn:          true,
				fadeOut:         true,
				posZEnd:         1,
				posZStartRand:   5,
				posZStartMiddle: 6,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:           effectPrimitive3D,
				spriteFile:     "data/sprite/\xC0\xCC\xC6\xD1\xC6\xAE/particle1",
				spriteRepeat:   true,
				duration:       250 * time.Millisecond,
				duplicate:      5,
				duplicateDelay: 20 * time.Millisecond,
				toSrc:          true,
				rotateToTarget: true,
				arc:            4,
				retreat:        3,
				posZ:           3,
				sizeStart:      100 * roBrowserEffectPixelRatio,
				sizeEnd:        roBrowserEffectSize(500),
			},
		},
	},
	effectEndure: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_endure.wav"},
		components: []worldEffectComponent{{
			kind:        effectPrimitiveBillboard,
			textureFile: "effect\\endure.tga",
			duration:    1000 * time.Millisecond,
			alphaMax:    1,
			fadeIn:      true,
			fadeOut:     true,
			posZ:        2,
			sizeStart:   2.0,
			sizeEnd:     0.7,
			sizeSmooth:  true,
		}},
	},
	effectBashBegin: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_bash.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_down",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.1,
				topSize:          2.0,
				posZ:             1.5,
				totalCircleSides: 20,
				circleSides:      20,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_center",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.01,
				topSize:          2.5,
				posZ:             1.5,
				totalCircleSides: 30,
				circleSides:      1,
				duplicate:        10,
				angleZRandom:     360,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha_center",
				duration:         1000 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				fixedPerspective: true,
				animation:        2,
				bottomSize:       0.01,
				topSize:          4.0,
				posZ:             1.5,
				totalCircleSides: 30,
				circleSides:      1,
				duplicate:        8,
				angleZRandom:     360,
			},
		},
	},
	effectProvoke: {
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\swordman_provoke.wav"},
		components: []worldEffectComponent{{
			kind:    effectPrimitiveSTR,
			color:   color.RGBA{R: 255, G: 70, B: 42, A: 255},
			strFile: "provoke",
		}},
	},
	effectMagnumBreak: {
		duration: 300 * time.Millisecond,
		sfx:      []string{"effect\\ef_magnumbreak.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "ring_yellow",
				duration:         300 * time.Millisecond,
				alphaMax:         0.7,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       4,
				topSize:          6,
				height:           1,
				totalCircleSides: 32,
				circleSides:      32,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "\xb4\xeb\xc6\xf8\xb9\xdf",
				duration:         300 * time.Millisecond,
				alphaMax:         0.6,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       4,
				topSize:          1,
				height:           4,
				totalCircleSides: 32,
				circleSides:      32,
			},
		},
	},
	effectSteal: {
		duration: 500 * time.Millisecond,
		sfx:      []string{"effect\\ef_steal.wav"},
		components: []worldEffectComponent{{
			kind:          effectPrimitive3D,
			color:         color.RGBA{R: 255, G: 255, B: 216, A: 255},
			textureFile:   "effect/pok1.tga",
			duration:      500 * time.Millisecond,
			alphaMax:      1,
			fadeOut:       true,
			posXEndRand:   3.5,
			posYEndRand:   3.5,
			posZEndRand:   1,
			posZEndMiddle: 3,
			sizeStart:     200 * roBrowserEffectPixelRatio,
			sizeEnd:       10 * roBrowserEffectPixelRatio,
			duplicate:     7,
		}},
	},
	effectPoisonAttack: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_detoxication.wav"},
		components: []worldEffectComponent{{
			kind:        effectPrimitive3D,
			color:       color.RGBA{R: 255, G: 178, B: 255, A: 255},
			textureFile: "effect/pok1.tga",
			duration:    1000 * time.Millisecond,
			alphaMax:    1,
			fadeIn:      true,
			fadeOut:     true,
			posXRand:    1,
			posYRand:    1,
			posZEnd:     5,
			sizeStart:   100 * roBrowserEffectPixelRatio,
			sizeEnd:     100 * roBrowserEffectPixelRatio,
			sizeRand:    20 * roBrowserEffectPixelRatio,
			duplicate:   10,
		}},
	},
	effectDetoxication: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_detoxication.wav"},
		components: []worldEffectComponent{{
			kind:        effectPrimitive3D,
			color:       color.RGBA{R: 178, G: 255, B: 255, A: 255},
			textureFile: "effect/pok1.tga",
			duration:    1000 * time.Millisecond,
			alphaMax:    1,
			fadeIn:      true,
			fadeOut:     true,
			posXRand:    1,
			posYRand:    1,
			posZEnd:     5,
			sizeStart:   100 * roBrowserEffectPixelRatio,
			sizeEnd:     100 * roBrowserEffectPixelRatio,
			sizeRand:    20 * roBrowserEffectPixelRatio,
			duplicate:   10,
		}},
	},
	effectStoneCurse: strEffectSpec("stonecurse", ""),
	effectColdBolt: {
		duration: 1000 * time.Millisecond,
		sfx:      []string{"effect\\ef_icearrow1.wav", "effect\\ef_icearrow2.wav", "effect\\ef_icearrow3.wav"},
		components: []worldEffectComponent{
			{
				kind:        effectPrimitive3D,
				textureFile: "effect/icearrow.tga",
				duration:    500 * time.Millisecond,
				alphaMax:    1,
				posX:        5,
				posY:        2,
				posZ:        20,
				posXEnd:     0.0001,
				posYEnd:     0.0001,
				posZEnd:     0,
				sizeStart:   50 * roBrowserEffectPixelRatio,
				sizeEnd:     50 * roBrowserEffectPixelRatio,
				angleStart:  112.5,
				angleEnd:    112.5,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "ring_blue",
				duration:         500 * time.Millisecond,
				delay:            500 * time.Millisecond,
				alphaMax:         0.7,
				fade:             true,
				rotate:           true,
				animation:        4,
				bottomSize:       3,
				topSize:          5,
				height:           0.1,
				totalCircleSides: 32,
				circleSides:      32,
				color:            color.RGBA{R: 128, G: 170, B: 255, A: 255},
			},
		},
	},
	effectFireBolt: {
		duration: 500 * time.Millisecond,
		sfx:      []string{"effect\\ef_firearrow1.wav", "effect\\ef_firearrow2.wav", "effect\\ef_firearrow3.wav"},
		components: []worldEffectComponent{{
			kind: effectPrimitive3D,
			textureFiles: []string{
				"effect/\xba\xd2\xc8\xad\xbb\xec1.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec2.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec3.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec4.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec5.tga",
				"effect/\xba\xd2\xc8\xad\xbb\xec6.tga",
			},
			duration:   500 * time.Millisecond,
			alphaMax:   1,
			posX:       5,
			posY:       2,
			posZ:       20,
			posXEnd:    0.0001,
			posYEnd:    0.0001,
			posZEnd:    0,
			sizeStart:  100 * roBrowserEffectPixelRatio,
			sizeEnd:    100 * roBrowserEffectPixelRatio,
			angleStart: 112.5,
			angleEnd:   112.5,
		}},
	},
	effectFireBall: {
		duration: 410 * time.Millisecond,
		sfx:      []string{"effect\\ef_fireball.wav"},
		components: []worldEffectComponent{{
			kind:           effectPrimitive3D,
			spriteFile:     "fireball",
			spriteRepeat:   true,
			toSrc:          true,
			rotateToTarget: true,
			duration:       250 * time.Millisecond,
			delay:          160 * time.Millisecond,
			alphaMax:       0.2,
			posZ:           2,
			sizeStart:      200 * roBrowserEffectPixelRatio,
			sizeEnd:        200 * roBrowserEffectPixelRatio,
			duplicate:      5,
		}},
	},
	effectFireWall: strEffectSpecRandom("firewall%d", "effect\\ef_firewall.wav", 1, 2),
	effectFrostDiver: {
		duration: 450 * time.Millisecond,
		sfx:      []string{"effect\\ef_frostdiver.wav"},
		components: []worldEffectComponent{{
			kind:        effectPrimitive3D,
			textureFile: "effect/ice.tga",
			duration:    450 * time.Millisecond,
			toSrc:       true,
			alphaMax:    0.75,
			fadeOut:     true,
			posZ:        0.7,
			posZEnd:     0.9,
			sizeStart:   90 * roBrowserEffectPixelRatio,
			sizeEnd:     130 * roBrowserEffectPixelRatio,
			angleStart:  0,
			angleEnd:    -180,
		}},
	},
	effectFrostDiverHit: strEffectSpec("freeze", "effect\\ef_frostdiver2.wav"),
	effectLightningBolt: {
		components: []worldEffectComponent{
			{
				kind:    effectPrimitiveSTR,
				strFile: "lightning",
			},
			{
				kind:       effectPrimitiveSTR,
				strFile:    "windhit%d",
				strRandMin: 1,
				strRandMax: 3,
			},
		},
	},
	effectThunderStorm: strEffectSpec("thunderstorm", "effect\\magician_thunderstorm.wav"),
	effectIncAgility: {
		duration: 1500 * time.Millisecond,
		sfx:      []string{"effect\\ef_incagility.wav"},
		components: []worldEffectComponent{
			incAgilityParticleComponent(1, 500*time.Millisecond, 7),
			incAgilityParticleComponent(0.75, 400*time.Millisecond, 3),
			incAgilityParticleComponent(1, 0, 10),
			{
				kind:        effectPrimitive3D,
				color:       color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile: "effect/agi_up.bmp",
				duration:    1000 * time.Millisecond,
				alphaMax:    1,
				fadeIn:      true,
				fadeOut:     true,
				posZ:        0.4,
				posZEnd:     3,
				sizeStart:   100 * roBrowserEffectPixelRatio,
				sizeEnd:     100 * roBrowserEffectPixelRatio,
				sizeSmooth:  true,
			},
		},
	},
	effectDecAgility: soundOnlyEffectSpec("effect\\ef_decagility.wav"),
	effectAqua: {
		sfx: []string{"effect\\ef_aqua.wav"},
		components: []worldEffectComponent{{
			kind:       effectPrimitiveSPR,
			spriteFile: "\xBC\xBA\xBC\xF6\xB6\xDF\xB1\xE2",
			spriteHead: true,
		}},
	},
	effectSignum:  strEffectSpec("cross", "effect\\ef_signum.wav"),
	effectAngelus: strEffectSpec("angelus", "effect\\ef_angelus.wav"),
	effectBlessing: {
		duration: 2500 * time.Millisecond,
		sfx:      []string{"effect\\ef_blessing.wav"},
		components: []worldEffectComponent{
			{
				kind:          effectPrimitiveSPR,
				spriteFile:    "\xC3\xE0\xBA\xB9",
				duration:      1500 * time.Millisecond,
				spriteDelay:   30 * time.Millisecond,
				spriteRepeat:  true,
				spriteHead:    true,
				spriteYOffset: -120,
			},
			{
				kind:            effectPrimitive3D,
				spriteFile:      "particle6",
				duration:        1200 * time.Millisecond,
				delay:           300 * time.Millisecond,
				duplicate:       6,
				duplicateDelay:  0,
				alphaMax:        1,
				fadeIn:          true,
				fadeOut:         true,
				posXRand:        1.2,
				posYRand:        1,
				posZStartRand:   2,
				posZStartMiddle: 5.5,
				posZEndRand:     0.5,
				posZEndMiddle:   1,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:            effectPrimitive3D,
				spriteFile:      "particle6",
				duration:        1200 * time.Millisecond,
				delay:           400 * time.Millisecond,
				duplicate:       6,
				duplicateDelay:  0,
				alphaMax:        1,
				fadeIn:          true,
				fadeOut:         true,
				posXRand:        1.4,
				posYRand:        1.1,
				posZStartRand:   2,
				posZStartMiddle: 5.5,
				posZEndRand:     0.5,
				posZEndMiddle:   1,
				sizeStart:       50 * roBrowserEffectPixelRatio,
				sizeEnd:         50 * roBrowserEffectPixelRatio,
			},
			{
				kind:        effectPrimitive3D,
				color:       color.RGBA{R: 25, G: 191, B: 255, A: 255},
				textureFile: "effect/pok2.tga",
				duration:    2500 * time.Millisecond,
				alphaMax:    0.3,
				fadeIn:      true,
				fadeOut:     true,
				sizeStart:   140 * roBrowserEffectPixelRatio,
				sizeEnd:     140 * roBrowserEffectPixelRatio,
			},
		},
	},
	effectFireHit: strEffectSpecRandom("firehit%d", "effect\\ef_firehit.wav", 1, 3),
	effectFireSplashHit: {
		duration: 500 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:        effectPrimitive2D,
			textureFile: "effect/firering.tga",
			duration:    500 * time.Millisecond,
			fadeOut:     true,
			posZ:        1,
			sizeStart:   10 * roBrowserEffectPixelRatio,
			sizeEnd:     300 * roBrowserEffectPixelRatio,
			angleStart:  0,
			angleEnd:    -360,
		}},
	},
	effectColdHit:       soundOnlyEffectSpec("_hit_fist3.wav", "_hit_fist4.wav"),
	effectWindHit:       strEffectSpecRandom("windhit%d", "", 1, 3),
	effectCure:          strEffectSpec("cure", "effect\\acolyte_cure.wav"),
	effectConcentration: strEffectSpec("concentration", "effect\\ac_concentration.wav"),
	effectRefineOK:      strEffectSpec("bs_refinesuccess", "effect\\bs_refinesuccess.wav"),
	effectRefineFail:    strEffectSpec("bs_refinefailed", "effect\\bs_refinefailed.wav"),
	effectEnergyCoat:    strEffectSpec("energycoat", ""),
	effectTeleportation: {
		duration: 1500 * time.Millisecond,
		sfx:      []string{"effect\\ef_teleportation.wav"},
		components: []worldEffectComponent{
			teleportCylinderComponent(0.3, 0.3, 35),
			teleportCylinderComponent(0.6, 0.8, 25),
			teleportCylinderComponent(0.8, 1.0, 13),
			teleportCylinderComponent(1.0, 1.3, 5),
		},
	},
	effectPortal: {
		duration: 25000 * time.Millisecond,
		sfx:      []string{"effect\\ef_readyportal.wav", "effect\\ef_portal.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "ring_blue",
				duration:         500 * time.Millisecond,
				alphaMax:         0.4,
				fadeOut:          true,
				rotate:           true,
				animation:        4,
				bottomSize:       2.4,
				topSize:          3.9,
				height:           0.1,
				posZ:             0.1,
				totalCircleSides: 32,
				circleSides:      32,
			},
			portalCylinderComponent(0.6, 0.6, 15, 0, "ring_blue", 0.3),
			portalCylinderComponent(0.8, 0.8, 13, 0, "ring_blue", 0.3),
			{
				kind:             effectPrimitiveCylinder,
				textureName:      "alpha1",
				duration:         25000 * time.Millisecond,
				alphaMax:         0.5,
				fade:             true,
				rotate:           true,
				animation:        0,
				bottomSize:       1,
				topSize:          1,
				height:           1,
				posZ:             2,
				totalCircleSides: 20,
				circleSides:      10,
			},
		},
	},
	effectPharmacyOK:   strEffectSpec("p_success", "effect\\p_success.wav"),
	effectPharmacyFail: strEffectSpec("p_failed", "effect\\p_failed.wav"),
	effectHeal: {
		duration: 1840 * time.Millisecond,
		sfx:      []string{"_heal_effect.wav"},
		components: []worldEffectComponent{
			healCylinderComponent(0.95, 0.95, 8),
			healCylinderComponent(1.0, 1.0, 8),
			{
				kind:           effectPrimitive3D,
				color:          color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile:    "effect/pok3.tga",
				duration:       1300 * time.Millisecond,
				delay:          400 * time.Millisecond,
				duplicateDelay: 10 * time.Millisecond,
				alphaMax:       0.6,
				fadeIn:         true,
				fadeOut:        true,
				posXRand:       1.5,
				posYRand:       1.5,
				posZEndRand:    2,
				posZEndMiddle:  6,
				sizeStart:      9 * roBrowserEffectPixelRatio,
				sizeEnd:        9 * roBrowserEffectPixelRatio,
				sizeRand:       2 * roBrowserEffectPixelRatio,
				duplicate:      15,
			},
			{
				kind:           effectPrimitive3D,
				color:          color.RGBA{R: 255, G: 255, B: 255, A: 255},
				textureFile:    "effect/pok3.tga",
				duration:       1100 * time.Millisecond,
				delay:          200 * time.Millisecond,
				duplicateDelay: 50 * time.Millisecond,
				alphaMax:       0.6,
				fadeIn:         true,
				fadeOut:        true,
				posXRand:       1,
				posYRand:       1,
				posZEnd:        5,
				posZStartRand:  1,
				sizeStart:      9 * roBrowserEffectPixelRatio,
				sizeEnd:        9 * roBrowserEffectPixelRatio,
				sizeRand:       2 * roBrowserEffectPixelRatio,
				duplicate:      7,
			},
		},
	},
	effectBaseLevelUp: {
		duration: 1300 * time.Millisecond,
		sfx:      []string{"levelup.wav"},
		components: []worldEffectComponent{{
			kind:    effectPrimitiveSTR,
			strFile: "angel",
		}},
	},
	effectJobLevelUp: {
		components: []worldEffectComponent{{
			kind:    effectPrimitiveSTR,
			strFile: "joblvup",
		}},
	},
	effectPotionRed:    potionEffectSpec("\xbb\xa1\xb0\xa3\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 82, B: 70, A: 255}),
	effectPotionOrange: potionEffectSpec("\xc1\xd6\xc8\xab\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 145, B: 58, A: 255}),
	effectPotionYellow: potionEffectSpec("\xb3\xeb\xb6\xf5\xc6\xf7\xbc\xc7", color.RGBA{R: 255, G: 226, B: 76, A: 255}),
	effectPotionWhite:  potionEffectSpec("\xc7\xcf\xbe\xe1\xc6\xf7\xbc\xc7", color.RGBA{R: 245, G: 245, B: 255, A: 255}),
	effectPotionBlue:   bluePotionEffectSpec(),
	effectPotionGreen:  potionEffectSpec("\xc3\xca\xb7\xcf\xc6\xf7\xbc\xc7", color.RGBA{R: 78, G: 225, B: 98, A: 255}),
	effectFood: {
		duration: 850 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:    effectPrimitiveSTR,
			color:   color.RGBA{R: 255, G: 182, B: 86, A: 255},
			strFile: "fruit",
		}},
	},
	effectFoodBlue: {
		duration: 850 * time.Millisecond,
		components: []worldEffectComponent{{
			kind:    effectPrimitiveSTR,
			color:   color.RGBA{R: 132, G: 112, B: 255, A: 255},
			strFile: "fruit",
		}},
	},
}

type effectCoverage struct {
	Implemented     int
	RobrowserActive int
	RobrowserAll    int
	ActivePercent   float64
	AllPercent      float64
}

func effectCoverageSnapshot() effectCoverage {
	implemented := len(worldEffectSpecs)
	return effectCoverage{
		Implemented:     implemented,
		RobrowserActive: robrowserActiveEffectTableEntries,
		RobrowserAll:    robrowserNumericEffectConstants,
		ActivePercent:   float64(implemented) / float64(robrowserActiveEffectTableEntries) * 100,
		AllPercent:      float64(implemented) / float64(robrowserNumericEffectConstants) * 100,
	}
}

func castAuraEffectSpec(texture string, tint color.RGBA, alphaMax, height, topSize float64) worldEffectSpec {
	return worldEffectSpec{
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\ef_beginspell.wav"},
		components: []worldEffectComponent{{
			kind:             effectPrimitiveCylinder,
			textureName:      texture,
			duration:         900 * time.Millisecond,
			alphaMax:         alphaMax,
			fade:             true,
			rotate:           true,
			animation:        2,
			bottomSize:       1,
			topSize:          topSize,
			height:           height,
			totalCircleSides: 32,
			circleSides:      32,
			color:            tint,
		}},
	}
}

func elementalCastAuraEffectSpec(texture string, tint color.RGBA, alphaMax float64) worldEffectSpec {
	return worldEffectSpec{
		duration: 900 * time.Millisecond,
		sfx:      []string{"effect\\ef_beginspell.wav"},
		components: []worldEffectComponent{
			{
				kind:             effectPrimitiveCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         0.3,
				fade:             true,
				rotate:           true,
				animation:        1,
				bottomSize:       1,
				topSize:          1,
				height:           30,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         alphaMax,
				fade:             true,
				rotate:           true,
				animation:        1,
				bottomSize:       1,
				topSize:          1.3,
				height:           2,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
			{
				kind:             effectPrimitiveCylinder,
				textureName:      texture,
				duration:         900 * time.Millisecond,
				alphaMax:         alphaMax,
				fade:             true,
				rotate:           true,
				animation:        2,
				bottomSize:       1,
				topSize:          4,
				height:           3,
				totalCircleSides: 32,
				circleSides:      32,
				color:            tint,
			},
		},
	}
}

func bluePotionEffectSpec() worldEffectSpec {
	spec := potionEffectSpec("\xc6\xc4\xb6\xf5\xc6\xf7\xbc\xc7", color.RGBA{R: 92, G: 150, B: 255, A: 255})
	spec.sfx = []string{"effect\\\xc8\xed\xb1\xe2.wav"}
	return spec
}

func incAgilityParticleComponent(alpha float64, delay time.Duration, duplicate int) worldEffectComponent {
	return worldEffectComponent{
		kind:            effectPrimitive3D,
		color:           color.RGBA{R: 255, G: 255, B: 255, A: 255},
		textureFile:     "effect/ac_center2.tga",
		duration:        1000 * time.Millisecond,
		delay:           delay,
		duplicateDelay:  80 * time.Millisecond,
		alphaMax:        alpha,
		fadeOut:         true,
		posXRand:        1.5,
		posYRand:        1,
		posZStartRand:   1,
		posZStartMiddle: 1,
		posZEndRand:     1,
		posZEndMiddle:   6,
		sizeStart:       45 * roBrowserEffectPixelRatio,
		sizeEnd:         45 * roBrowserEffectPixelRatio,
		sizeRand:        15 * roBrowserEffectPixelRatio,
		duplicate:       duplicate,
	}
}
