package db

// skillSelectableLevels mirrors the reference client's bSeperateLv=true
// metadata for every skill in Goro's pre-renewal player skill trees. Skills
// present in SkillMaxLevels but absent here are known fixed-level skills.
var skillSelectableLevels = map[uint16]struct{}{
	SkillSMBash:            {},
	SkillSMProvoke:         {},
	SkillKNSpearstab:       {},
	SkillKNTwohandquicken:  {},
	SkillKNBowlingbash:     {},
	SkillLKSpiralpierce:    {},
	SkillLKJointbeat:       {},
	SkillLKAurablade:       {},
	SkillLKParrying:        {},
	SkillLKConcentration:   {},
	SkillCRAutoguard:       {},
	SkillCRReflectshield:   {},
	SkillCRHolycross:       {},
	SkillCRGrandcross:      {},
	SkillCRSpearquicken:    {},
	SkillPaPressure:        {},
	SkillPaShieldchain:     {},
	SkillPaGospel:          {},
	SkillMGSafetywall:      {},
	SkillMGSoulstrike:      {},
	SkillMGColdbolt:        {},
	SkillMGFirebolt:        {},
	SkillMGLightningbolt:   {},
	SkillMGThunderstorm:    {},
	SkillWZFirepillar:      {},
	SkillWZSightrasher:     {},
	SkillWZMeteor:          {},
	SkillWZJupitel:         {},
	SkillWZVermilion:       {},
	SkillWZWaterball:       {},
	SkillWZStormgust:       {},
	SkillWZEarthspike:      {},
	SkillWZHeavendrive:     {},
	SkillHWMagicpower:      {},
	SkillHWNapalmvulcan:    {},
	SkillHWGravitation:     {},
	SkillPFSoulburn:        {},
	SkillPFMindbreaker:     {},
	SkillALTeleport:        {},
	SkillALHeal:            {},
	SkillALIncagi:          {},
	SkillALDecagi:          {},
	SkillALAngelus:         {},
	SkillALBlessing:        {},
	SkillPRImpositio:       {},
	SkillPRSuffragium:      {},
	SkillPRAspersio:        {},
	SkillPRSanctuary:       {},
	SkillPRSlowpoison:      {},
	SkillPRKyrie:           {},
	SkillPRMagnus:          {},
	SkillHPAssumptio:       {},
	SkillHPBasilica:        {},
	SkillMOInvestigate:     {},
	SkillMOFingeroffensive: {},
	SkillMOChaincombo:      {},
	SkillMOCombofinish:     {},
	SkillChPalmstrike:      {},
	SkillChTigerfist:       {},
	SkillChChaincrush:      {},
	SkillMCMammonite:       {},
	SkillBSAdrenaline:      {},
	SkillBSOverthrust:      {},
	SkillWSMeltdown:        {},
	SkillACConcentration:   {},
	SkillHTSkidtrap:        {},
	SkillHTLandmine:        {},
	SkillHTAnklesnare:      {},
	SkillHTShockwave:       {},
	SkillHTSandman:         {},
	SkillHTFlasher:         {},
	SkillHTFreezingtrap:    {},
	SkillHTBlastmine:       {},
	SkillHTClaymoretrap:    {},
	SkillHTBlitzbeat:       {},
	SkillSNSight:           {},
	SkillSNFalconassault:   {},
	SkillSNSharpshooting:   {},
	SkillSNWindwalk:        {},
	SkillTFHiding:          {},
	SkillRGStripweapon:     {},
	SkillRGStripshield:     {},
	SkillRGStriparmor:      {},
	SkillRGStriphelm:       {},
	SkillRGIntimidate:      {},
	SkillSTRejectsword:     {},
	SkillSTFullstrip:       {},
	SkillASSonicblow:       {},
	SkillASSplasher:        {},
	SkillASCEdp:            {},
	SkillASCBreaker:        {},
	SkillASCMeteorassault:  {},
	SkillAMPotionpitcher:   {},
	SkillAMCannibalize:     {},
	SkillAMResurrecthomun:  {},
	SkillCRSlimpitcher:     {},
	SkillCRCultivation:     {},
	SkillBDDrumbattlefield: {},
	SkillBDRingnibelungen:  {},
	SkillBaMusicalstrike:   {},
	SkillBaDissonance:      {},
	SkillBaFrostjoke:       {},
	SkillBaWhistle:         {},
	SkillBaAssassincross:   {},
	SkillBaPoembragi:       {},
	SkillBaAppleidun:       {},
	SkillDCThrowarrow:      {},
	SkillDCUglydance:       {},
	SkillDCScream:          {},
	SkillDCHumming:         {},
	SkillDCDontforgetme:    {},
	SkillDCFortunekiss:     {},
	SkillDCServiceforyou:   {},
	SkillCGArrowvulcan:     {},
	SkillCGMoonlit:         {},
	SkillTKSevenwind:       {},
	SkillTKHighjump:        {},
	SkillSGFeel:            {},
	SkillSGHate:            {},
	SkillSLKaahi:           {},
	SkillSLStin:            {},
	SkillSLStun:            {},
	SkillSLSma:             {},
	SkillNJHuuma:           {},
	SkillNJZenynage:        {},
	SkillNJKasumikiri:      {},
	SkillNJKirikage:        {},
	SkillNJUtsusemi:        {},
	SkillNJBunsinjyutsu:    {},
	SkillNJKouenka:         {},
	SkillNJBakuenryu:       {},
	SkillNJHyousensou:      {},
	SkillNJSuiton:          {},
	SkillNJHyousyouraku:    {},
	SkillNJHuujin:          {},
	SkillNJRaigekisai:      {},
	SkillNJKamaitachi:      {},
	SkillNJNen:             {},
	SkillNJIssen:           {},
}

func SkillLevelSelectable(skillID uint16) (bool, bool) {
	if _, selectable := skillSelectableLevels[skillID]; selectable {
		return true, true
	}
	_, known := SkillMaxLevel(skillID)
	return false, known
}

// SkillAttackRanges mirrors roBrowser's DB/Skills/SkillInfo.js AttackRange rows.
// It is intentionally sparse so broader SkillInfo metadata can be batch-imported later.
var SkillAttackRanges = map[uint16][]int{
	SkillWEMale:             {9},
	SkillWEFemale:           {9},
	SkillWECallpartner:      {1},
	SkillWEBaby:             {9},
	SkillWECallparent:       {1},
	SkillWECallbaby:         {1},
	SkillTKRun:              repeatedSkillRange(1, 10),
	SkillTKReadystorm:       {1},
	SkillTKStormkick:        repeatedSkillRange(1, 7),
	SkillTKReadydown:        {1},
	SkillTKDownkick:         repeatedSkillRange(1, 7),
	SkillTKReadyturn:        {1},
	SkillTKTurnkick:         repeatedSkillRange(1, 7),
	SkillTKReadycounter:     {1},
	SkillTKCounter:          repeatedSkillRange(1, 7),
	SkillTKDodge:            {1},
	SkillTKJumpkick:         repeatedSkillRange(9, 7),
	SkillTKHptime:           repeatedSkillRange(1, 10),
	SkillTKSptime:           repeatedSkillRange(1, 10),
	SkillTKPower:            repeatedSkillRange(1, 5),
	SkillTKSevenwind:        repeatedSkillRange(1, 7),
	SkillTKHighjump:         {2, 4, 6, 8, 10},
	SkillTKMission:          {1},
	SkillSGFeel:             repeatedSkillRange(1, 3),
	SkillSGSunWarm:          repeatedSkillRange(1, 3),
	SkillSGMoonWarm:         repeatedSkillRange(1, 3),
	SkillSGStarWarm:         repeatedSkillRange(1, 3),
	SkillSGSunComfort:       repeatedSkillRange(1, 4),
	SkillSGMoonComfort:      repeatedSkillRange(1, 4),
	SkillSGStarComfort:      repeatedSkillRange(1, 4),
	SkillSGHate:             repeatedSkillRange(9, 3),
	SkillSGSunAnger:         repeatedSkillRange(1, 3),
	SkillSGMoonAnger:        repeatedSkillRange(1, 3),
	SkillSGStarAnger:        repeatedSkillRange(1, 3),
	SkillSGSunBless:         repeatedSkillRange(1, 5),
	SkillSGMoonBless:        repeatedSkillRange(1, 5),
	SkillSGStarBless:        repeatedSkillRange(1, 5),
	SkillSGDevil:            repeatedSkillRange(1, 10),
	SkillSGFriend:           repeatedSkillRange(1, 3),
	SkillSGKnowledge:        repeatedSkillRange(1, 10),
	SkillSGFusion:           {1},
	SkillSLAlchemist:        repeatedSkillRange(9, 5),
	SkillSLMonk:             repeatedSkillRange(9, 5),
	SkillSLStar:             repeatedSkillRange(9, 5),
	SkillSLSage:             repeatedSkillRange(9, 5),
	SkillSLCrusader:         repeatedSkillRange(9, 5),
	SkillSLSupernovice:      repeatedSkillRange(9, 5),
	SkillSLKnight:           repeatedSkillRange(9, 5),
	SkillSLWizard:           repeatedSkillRange(9, 5),
	SkillSLPriest:           repeatedSkillRange(9, 5),
	SkillSLBarddancer:       repeatedSkillRange(9, 5),
	SkillSLRogue:            repeatedSkillRange(9, 5),
	SkillSLAssasin:          repeatedSkillRange(9, 5),
	SkillSLBlacksmith:       repeatedSkillRange(9, 5),
	SkillSLHunter:           repeatedSkillRange(9, 5),
	SkillSLSoullinker:       repeatedSkillRange(9, 5),
	SkillSLKaizel:           repeatedSkillRange(9, 7),
	SkillSLKaahi:            repeatedSkillRange(9, 7),
	SkillSLKaupe:            repeatedSkillRange(9, 3),
	SkillSLKaite:            repeatedSkillRange(9, 7),
	SkillSLKaina:            repeatedSkillRange(1, 7),
	SkillSLStin:             repeatedSkillRange(9, 7),
	SkillSLStun:             repeatedSkillRange(9, 7),
	SkillSLSma:              repeatedSkillRange(9, 10),
	SkillSLSwoo:             repeatedSkillRange(9, 7),
	SkillSLSke:              repeatedSkillRange(9, 3),
	SkillSLSka:              repeatedSkillRange(9, 3),
	SkillSLHigh:             repeatedSkillRange(9, 5),
	SkillNJTobidougu:        repeatedSkillRange(1, 10),
	SkillNJSyuriken:         repeatedSkillRange(9, 10),
	SkillNJKunai:            repeatedSkillRange(9, 5),
	SkillNJHuuma:            repeatedSkillRange(9, 5),
	SkillNJZenynage:         repeatedSkillRange(7, 10),
	SkillNJTatamigaeshi:     repeatedSkillRange(1, 5),
	SkillNJKasumikiri:       repeatedSkillRange(1, 10),
	SkillNJShadowjump:       {6, 8, 10, 12, 14},
	SkillNJKirikage:         repeatedSkillRange(1, 5),
	SkillNJUtsusemi:         repeatedSkillRange(1, 5),
	SkillNJBunsinjyutsu:     repeatedSkillRange(1, 10),
	SkillNJNinpou:           repeatedSkillRange(1, 10),
	SkillNJKouenka:          repeatedSkillRange(9, 10),
	SkillNJKaensin:          repeatedSkillRange(1, 10),
	SkillNJBakuenryu:        repeatedSkillRange(9, 5),
	SkillNJHyousensou:       repeatedSkillRange(9, 10),
	SkillNJSuiton:           repeatedSkillRange(9, 10),
	SkillNJHyousyouraku:     repeatedSkillRange(1, 5),
	SkillNJHuujin:           repeatedSkillRange(9, 10),
	SkillNJRaigekisai:       repeatedSkillRange(9, 5),
	SkillNJKamaitachi:       {5, 6, 7, 8, 9},
	SkillNJNen:              repeatedSkillRange(1, 5),
	SkillNJIssen:            repeatedSkillRange(5, 10),
	SkillHlifHeal:           {1, 1, 1, 1, 1},
	SkillHlifAvoid:          {1, 1, 1, 1, 1},
	SkillHlifBrain:          {1, 1, 1, 1, 1},
	SkillHlifChange:         {1, 1, 1},
	SkillHamiCastle:         {1, 1, 1, 1, 1},
	SkillHamiDefence:        {1, 1, 1, 1, 1},
	SkillHamiSkin:           {1, 1, 1, 1, 1},
	SkillHamiBloodlust:      {1, 1, 1},
	SkillHfliMoon:           {1, 1, 1, 1, 1},
	SkillHfliFleet:          {1, 1, 1, 1, 1},
	SkillHfliSpeed:          {1, 1, 1, 1, 1},
	SkillHfliSbr44:          {9, 9, 9},
	SkillHvanCaprice:        {9, 9, 9, 9, 9},
	SkillHvanChaotic:        {1, 1, 1, 1, 1},
	SkillHvanInstruct:       {1, 1, 1, 1, 1},
	SkillHvanExplosion:      {1, 1, 1},
	SkillMhSummonLegion:     {9, 9, 9, 9, 9},
	SkillMhNeedleOfParalyze: {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMhPoisonMist:       {5, 5, 5, 5, 5},
	SkillMhPainKiller:       {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMhLightOfRegene:    {1, 1, 1, 1, 1},
	SkillMhOveredBoost:      {1, 1, 1, 1, 1},
	SkillMhEraserCutter:     {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhXenoSlasher:      {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhSilentBreeze:     {5, 5, 7, 7, 9},
	SkillMhStyleChange:      {1},
	SkillMhSonicCraw:        {1, 1, 1, 1, 1},
	SkillMhSilverveinRush:   {3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
	SkillMhMidnightFrenzy:   {3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
	SkillMhStahlHorn:        {5, 5, 6, 6, 7, 7, 8, 8, 9, 9},
	SkillMhGoldeneFerse:     {1, 1, 1, 1, 1},
	SkillMhSteinwand:        {1, 1, 1, 1, 1},
	SkillMhHeiligeStange:    {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMhAngriffsModus:    {1, 1, 1, 1, 1},
	SkillMhTinderBreaker:    {3, 4, 5, 6, 7},
	SkillMhCbc:              {1, 1, 1, 1, 1},
	SkillMhEqc:              {1, 1, 1, 1, 1},
	SkillMhMagmaFlow:        {1, 1, 1, 1, 1},
	SkillMhGraniticArmor:    {1, 1, 1, 1, 1},
	SkillMhLavaSlide:        {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhPyroclastic:      {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMhVolcanicAsh:      {7, 7, 7, 7, 7},
	SkillMsBash:             {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsMagnum:           {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsBowlingbash:      {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMsParrying:         {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsReflectshield:    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsBerserk:          {1},
	SkillMaDouble:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMaShower:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMaSkidtrap:         {3, 3, 3, 3, 3},
	SkillMaLandmine:         {3, 3, 3, 3, 3},
	SkillMaSandman:          {3, 3, 3, 3, 3},
	SkillMaFreezingtrap:     {3, 3, 3, 3, 3},
	SkillMaRemovetrap:       {2},
	SkillMaChargearrow:      {9},
	SkillMaSharpshooting:    {9, 9, 9, 9, 9},
	SkillMlPierce:           {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMlBrandish:         {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMlSpiralpierce:     {4, 4, 4, 4, 4},
	SkillMlDefender:         {1, 1, 1, 1, 1},
	SkillMlAutoguard:        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMlDevotion:         {7, 8, 9, 10, 11},
	SkillMerMagnificat:      {1, 1, 1, 1, 1},
	SkillMerQuicken:         {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMerSight:           {1},
	SkillMerCrash:           {1, 1, 1, 1, 1},
	SkillMerRegain:          {9},
	SkillMerTender:          {9},
	SkillMerBenediction:     {9},
	SkillMerRecuperate:      {9},
	SkillMerMentalcure:      {9},
	SkillMerCompress:        {9},
	SkillMerProvoke:         {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerAutoberserk:     {1},
	SkillMerDecagi:          {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerScapegoat:       {1},
	SkillMerLexdivina:       {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMerEstimation:      {9},
	SkillMerKyrie:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerBlessing:        {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerIncagi:          {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerInvincibleoff2:  {2},
}

func repeatedSkillRange(value, count int) []int {
	ranges := make([]int, count)
	for i := range ranges {
		ranges[i] = value
	}
	return ranges
}

func SkillAttackRange(skillID uint16, level int) (int, bool) {
	ranges, ok := SkillAttackRanges[skillID]
	if !ok || level <= 0 || level > len(ranges) {
		return 0, false
	}
	return ranges[level-1], true
}
