package db

type SkillRequirement struct {
	SkillID uint16
	Level   int
}

var SkillRequirements = map[uint16][]SkillRequirement{
	SkillSMTwohand:        {{SkillID: SkillSMSword, Level: 1}},
	SkillSMMagnum:         {{SkillID: SkillSMBash, Level: 5}},
	SkillSMEndure:         {{SkillID: SkillSMProvoke, Level: 5}},
	SkillKNPierce:         {{SkillID: SkillKNSpearmastery, Level: 1}},
	SkillKNBrandishspear:  {{SkillID: SkillKNRiding, Level: 1}, {SkillID: SkillKNSpearstab, Level: 3}},
	SkillKNSpearstab:      {{SkillID: SkillKNPierce, Level: 5}},
	SkillKNSpearboomerang: {{SkillID: SkillKNPierce, Level: 3}},
	SkillKNTwohandquicken: {{SkillID: SkillSMTwohand, Level: 1}},
	SkillKNAutocounter:    {{SkillID: SkillSMTwohand, Level: 1}},
	SkillKNBowlingbash: {
		{SkillID: SkillSMBash, Level: 10},
		{SkillID: SkillSMMagnum, Level: 3},
		{SkillID: SkillSMTwohand, Level: 5},
		{SkillID: SkillKNTwohandquicken, Level: 10},
		{SkillID: SkillKNAutocounter, Level: 5},
	},
	SkillKNRiding:          {{SkillID: SkillSMEndure, Level: 1}},
	SkillKNCavaliermastery: {{SkillID: SkillKNRiding, Level: 1}},
	SkillKNOnehand:         {{SkillID: SkillKNTwohandquicken, Level: 10}},
	SkillLKSpiralpierce: {
		{SkillID: SkillKNSpearmastery, Level: 5},
		{SkillID: SkillKNPierce, Level: 5},
		{SkillID: SkillKNRiding, Level: 1},
		{SkillID: SkillKNSpearstab, Level: 5},
	},
	SkillLKHeadcrush:       {{SkillID: SkillKNSpearmastery, Level: 9}, {SkillID: SkillKNRiding, Level: 1}},
	SkillLKJointbeat:       {{SkillID: SkillKNCavaliermastery, Level: 3}, {SkillID: SkillLKHeadcrush, Level: 3}},
	SkillLKAurablade:       {{SkillID: SkillSMMagnum, Level: 5}, {SkillID: SkillSMTwohand, Level: 5}},
	SkillLKParrying:        {{SkillID: SkillSMProvoke, Level: 5}, {SkillID: SkillSMTwohand, Level: 10}, {SkillID: SkillKNTwohandquicken, Level: 3}},
	SkillLKConcentration:   {{SkillID: SkillSMRecovery, Level: 5}, {SkillID: SkillKNSpearmastery, Level: 5}, {SkillID: SkillKNRiding, Level: 1}},
	SkillLKTensionrelax:    {{SkillID: SkillSMProvoke, Level: 5}, {SkillID: SkillSMRecovery, Level: 10}, {SkillID: SkillSMEndure, Level: 3}},
	SkillCRShieldcharge:    {{SkillID: SkillCRAutoguard, Level: 5}},
	SkillCRShieldboomerang: {{SkillID: SkillCRShieldcharge, Level: 3}},
	SkillCRReflectshield:   {{SkillID: SkillCRShieldboomerang, Level: 3}},
	SkillCRHolycross:       {{SkillID: SkillCRTrust, Level: 7}},
	SkillCRGrandcross:      {{SkillID: SkillCRTrust, Level: 10}, {SkillID: SkillCRHolycross, Level: 6}},
	SkillCRDevotion:        {{SkillID: SkillCRGrandcross, Level: 4}, {SkillID: SkillCRReflectshield, Level: 5}},
	SkillCRProvidence:      {{SkillID: SkillALDp, Level: 5}, {SkillID: SkillALHeal, Level: 5}},
	SkillCRDefender:        {{SkillID: SkillCRShieldboomerang, Level: 1}},
	SkillCRSpearquicken:    {{SkillID: SkillKNSpearmastery, Level: 10}},
	SkillPaPressure: {
		{SkillID: SkillSMEndure, Level: 5},
		{SkillID: SkillCRTrust, Level: 5},
		{SkillID: SkillCRShieldcharge, Level: 2},
	},
	SkillPaShieldchain:    {{SkillID: SkillCRShieldboomerang, Level: 5}},
	SkillPaSacrifice:      {{SkillID: SkillSMEndure, Level: 1}, {SkillID: SkillCRDevotion, Level: 3}},
	SkillPaGospel:         {{SkillID: SkillCRTrust, Level: 8}, {SkillID: SkillALDp, Level: 3}, {SkillID: SkillALDemonbane, Level: 5}},
	SkillMGSafetywall:     {{SkillID: SkillMGNapalmbeat, Level: 7}, {SkillID: SkillMGSoulstrike, Level: 5}},
	SkillMGSoulstrike:     {{SkillID: SkillMGNapalmbeat, Level: 4}},
	SkillMGFrostdiver:     {{SkillID: SkillMGColdbolt, Level: 5}},
	SkillMGFireball:       {{SkillID: SkillMGFirebolt, Level: 4}},
	SkillMGFirewall:       {{SkillID: SkillMGSight, Level: 1}, {SkillID: SkillMGFireball, Level: 5}},
	SkillMGThunderstorm:   {{SkillID: SkillMGLightningbolt, Level: 4}},
	SkillWZFirepillar:     {{SkillID: SkillMGFirewall, Level: 1}},
	SkillWZSightrasher:    {{SkillID: SkillMGSight, Level: 1}, {SkillID: SkillMGLightningbolt, Level: 1}},
	SkillWZMeteor:         {{SkillID: SkillMGThunderstorm, Level: 1}, {SkillID: SkillWZSightrasher, Level: 2}},
	SkillWZJupitel:        {{SkillID: SkillMGNapalmbeat, Level: 1}, {SkillID: SkillMGLightningbolt, Level: 1}},
	SkillWZVermilion:      {{SkillID: SkillMGThunderstorm, Level: 1}, {SkillID: SkillWZJupitel, Level: 5}},
	SkillWZWaterball:      {{SkillID: SkillMGColdbolt, Level: 1}, {SkillID: SkillMGLightningbolt, Level: 1}},
	SkillWZIcewall:        {{SkillID: SkillMGStonecurse, Level: 1}, {SkillID: SkillMGFrostdiver, Level: 1}},
	SkillWZFrostnova:      {{SkillID: SkillWZIcewall, Level: 1}},
	SkillWZStormgust:      {{SkillID: SkillMGFrostdiver, Level: 1}, {SkillID: SkillWZJupitel, Level: 3}},
	SkillWZEarthspike:     {{SkillID: SkillMGStonecurse, Level: 1}},
	SkillWZHeavendrive:    {{SkillID: SkillWZEarthspike, Level: 3}},
	SkillWZQuagmire:       {{SkillID: SkillWZHeavendrive, Level: 1}},
	SkillHWSouldrain:      {{SkillID: SkillMGSrecovery, Level: 5}, {SkillID: SkillMGSoulstrike, Level: 7}},
	SkillHWMagiccrasher:   {{SkillID: SkillMGSrecovery, Level: 1}},
	SkillHWNapalmvulcan:   {{SkillID: SkillMGNapalmbeat, Level: 5}},
	SkillHWGanbantein:     {{SkillID: SkillWZEstimation, Level: 1}, {SkillID: SkillWZIcewall, Level: 1}},
	SkillHWGravitation:    {{SkillID: SkillWZQuagmire, Level: 1}, {SkillID: SkillHWMagiccrasher, Level: 1}, {SkillID: SkillHWMagicpower, Level: 10}},
	SkillALPneuma:         {{SkillID: SkillALWarp, Level: 4}},
	SkillALTeleport:       {{SkillID: SkillALRuwach, Level: 1}},
	SkillALWarp:           {{SkillID: SkillALTeleport, Level: 2}},
	SkillALIncagi:         {{SkillID: SkillALHeal, Level: 3}},
	SkillALDecagi:         {{SkillID: SkillALIncagi, Level: 1}},
	SkillALCrucis:         {{SkillID: SkillALDemonbane, Level: 3}},
	SkillALAngelus:        {{SkillID: SkillALDp, Level: 3}},
	SkillALBlessing:       {{SkillID: SkillALDp, Level: 5}},
	SkillALCure:           {{SkillID: SkillALHeal, Level: 2}},
	SkillALDemonbane:      {{SkillID: SkillALDp, Level: 3}},
	SkillALLResurrection:  {{SkillID: SkillMGSrecovery, Level: 4}, {SkillID: SkillPRStrecovery, Level: 1}},
	SkillPRSuffragium:     {{SkillID: SkillPRImpositio, Level: 2}},
	SkillPRAspersio:       {{SkillID: SkillALHolywater, Level: 1}, {SkillID: SkillPRImpositio, Level: 3}},
	SkillPRBenedictio:     {{SkillID: SkillPRAspersio, Level: 5}, {SkillID: SkillPRGloria, Level: 3}},
	SkillPRSanctuary:      {{SkillID: SkillALHeal, Level: 1}},
	SkillPRKyrie:          {{SkillID: SkillALAngelus, Level: 2}},
	SkillPRGloria:         {{SkillID: SkillPRKyrie, Level: 4}, {SkillID: SkillPRMagnificat, Level: 3}},
	SkillPRLexdivina:      {{SkillID: SkillALRuwach, Level: 1}},
	SkillPRTurnundead:     {{SkillID: SkillALLResurrection, Level: 1}, {SkillID: SkillPRLexdivina, Level: 3}},
	SkillPRLexaeterna:     {{SkillID: SkillPRLexdivina, Level: 5}},
	SkillPRMagnus:         {{SkillID: SkillMGSafetywall, Level: 1}, {SkillID: SkillPRLexaeterna, Level: 1}, {SkillID: SkillPRTurnundead, Level: 3}},
	SkillHPManarecharge:   {{SkillID: SkillPRMacemastery, Level: 10}, {SkillID: SkillALDemonbane, Level: 10}},
	SkillHPAssumptio:      {{SkillID: SkillALAngelus, Level: 1}, {SkillID: SkillMGSrecovery, Level: 3}, {SkillID: SkillPRImpositio, Level: 3}},
	SkillHPBasilica:       {{SkillID: SkillPRGloria, Level: 2}, {SkillID: SkillMGSrecovery, Level: 1}, {SkillID: SkillPRKyrie, Level: 3}},
	SkillHPMeditatio:      {{SkillID: SkillMGSrecovery, Level: 5}, {SkillID: SkillPRLexdivina, Level: 5}, {SkillID: SkillPRAspersio, Level: 3}},
	SkillMCDiscount:       {{SkillID: SkillMCInccarry, Level: 3}},
	SkillMCOvercharge:     {{SkillID: SkillMCDiscount, Level: 3}},
	SkillMCPushcart:       {{SkillID: SkillMCInccarry, Level: 5}},
	SkillMCVending:        {{SkillID: SkillMCPushcart, Level: 3}},
	SkillBSSteel:          {{SkillID: SkillBSIron, Level: 1}},
	SkillBSEnchantedstone: {{SkillID: SkillBSIron, Level: 1}},
	SkillBSOrideocon:      {{SkillID: SkillBSEnchantedstone, Level: 1}},
	SkillBSSword:          {{SkillID: SkillBSDagger, Level: 1}},
	SkillBSTwohandsword:   {{SkillID: SkillBSSword, Level: 1}},
	SkillBSAxe:            {{SkillID: SkillBSSword, Level: 2}},
	SkillBSMace:           {{SkillID: SkillBSKnuckle, Level: 1}},
	SkillBSKnuckle:        {{SkillID: SkillBSDagger, Level: 1}},
	SkillBSSpear:          {{SkillID: SkillBSDagger, Level: 2}},
	SkillBSFindingore:     {{SkillID: SkillBSHiltbinding, Level: 1}, {SkillID: SkillBSSteel, Level: 1}},
	SkillBSWeaponresearch: {{SkillID: SkillBSHiltbinding, Level: 1}},
	SkillBSRepairweapon:   {{SkillID: SkillBSWeaponresearch, Level: 1}},
	SkillBSAdrenaline:     {{SkillID: SkillBSHammerfall, Level: 2}},
	SkillBSWeaponperfect:  {{SkillID: SkillBSWeaponresearch, Level: 2}, {SkillID: SkillBSAdrenaline, Level: 2}},
	SkillBSOverthrust:     {{SkillID: SkillBSAdrenaline, Level: 3}},
	SkillBSMaximize:       {{SkillID: SkillBSWeaponperfect, Level: 3}, {SkillID: SkillBSOverthrust, Level: 2}},
	SkillBSAdrenaline2:    {{SkillID: SkillBSAdrenaline, Level: 5}},
	SkillWSMeltdown: {
		{SkillID: SkillBSSkintemper, Level: 3},
		{SkillID: SkillBSHiltbinding, Level: 1},
		{SkillID: SkillBSWeaponresearch, Level: 5},
		{SkillID: SkillBSOverthrust, Level: 3},
	},
	SkillWSCartboost: {
		{SkillID: SkillMCPushcart, Level: 5},
		{SkillID: SkillBSHiltbinding, Level: 1},
		{SkillID: SkillMCCartrevolution, Level: 1},
		{SkillID: SkillMCChangecart, Level: 1},
	},
	SkillWSWeaponrefine:    {{SkillID: SkillBSWeaponresearch, Level: 10}},
	SkillWSCarttermination: {{SkillID: SkillMCMammonite, Level: 10}, {SkillID: SkillBSHammerfall, Level: 5}, {SkillID: SkillWSCartboost, Level: 1}},
	SkillWSOverthrustmax:   {{SkillID: SkillBSOverthrust, Level: 5}},
	SkillACVulture:         {{SkillID: SkillACOwl, Level: 3}},
	SkillACConcentration:   {{SkillID: SkillACVulture, Level: 1}},
	SkillACShower:          {{SkillID: SkillACDouble, Level: 5}},
	SkillHTPower:           {{SkillID: SkillACDouble, Level: 10}},
	SkillHTAnklesnare:      {{SkillID: SkillHTSkidtrap, Level: 1}},
	SkillHTShockwave:       {{SkillID: SkillHTAnklesnare, Level: 1}},
	SkillHTSandman:         {{SkillID: SkillHTFlasher, Level: 1}},
	SkillHTFlasher:         {{SkillID: SkillHTSkidtrap, Level: 1}},
	SkillHTFreezingtrap:    {{SkillID: SkillHTFlasher, Level: 1}},
	SkillHTBlastmine: {
		{SkillID: SkillHTLandmine, Level: 1},
		{SkillID: SkillHTSandman, Level: 1},
		{SkillID: SkillHTFreezingtrap, Level: 1},
	},
	SkillHTClaymoretrap: {{SkillID: SkillHTShockwave, Level: 1}, {SkillID: SkillHTBlastmine, Level: 1}},
	SkillHTRemovetrap:   {{SkillID: SkillHTLandmine, Level: 1}},
	SkillHTTalkiebox:    {{SkillID: SkillHTRemovetrap, Level: 1}, {SkillID: SkillHTShockwave, Level: 1}},
	SkillHTFalcon:       {{SkillID: SkillHTBeastbane, Level: 1}},
	SkillHTSteelcrow:    {{SkillID: SkillHTBlitzbeat, Level: 5}},
	SkillHTBlitzbeat:    {{SkillID: SkillHTFalcon, Level: 1}},
	SkillHTDetecting:    {{SkillID: SkillACConcentration, Level: 1}, {SkillID: SkillHTFalcon, Level: 1}},
	SkillHTSpringtrap:   {{SkillID: SkillHTFalcon, Level: 1}, {SkillID: SkillHTRemovetrap, Level: 1}},
	SkillSNSight: {
		{SkillID: SkillACOwl, Level: 10},
		{SkillID: SkillACVulture, Level: 10},
		{SkillID: SkillACConcentration, Level: 10},
		{SkillID: SkillHTFalcon, Level: 1},
	},
	SkillSNFalconassault: {
		{SkillID: SkillACVulture, Level: 5},
		{SkillID: SkillHTFalcon, Level: 1},
		{SkillID: SkillHTBlitzbeat, Level: 5},
		{SkillID: SkillHTSteelcrow, Level: 3},
	},
	SkillSNSharpshooting: {{SkillID: SkillACDouble, Level: 5}, {SkillID: SkillACConcentration, Level: 10}},
	SkillSNWindwalk:      {{SkillID: SkillACConcentration, Level: 9}},
	SkillTFHiding:        {{SkillID: SkillTFSteal, Level: 5}},
	SkillTFDetoxify:      {{SkillID: SkillTFPoison, Level: 3}},
	SkillASLeft:          {{SkillID: SkillASRight, Level: 2}},
	SkillASCloaking:      {{SkillID: SkillTFHiding, Level: 2}},
	SkillASSonicblow:     {{SkillID: SkillASKatar, Level: 4}},
	SkillASGrimtooth:     {{SkillID: SkillASCloaking, Level: 2}, {SkillID: SkillASSonicblow, Level: 5}},
	SkillASEnchantpoison: {{SkillID: SkillTFPoison, Level: 1}},
	SkillASPoisonreact:   {{SkillID: SkillASEnchantpoison, Level: 3}},
	SkillASVenomdust:     {{SkillID: SkillASEnchantpoison, Level: 5}},
	SkillASSplasher:      {{SkillID: SkillASVenomdust, Level: 5}, {SkillID: SkillASPoisonreact, Level: 5}},
	SkillASCKatar:        {{SkillID: SkillTFDouble, Level: 5}, {SkillID: SkillASKatar, Level: 7}},
	SkillASCEdp:          {{SkillID: SkillASCCdp, Level: 1}},
	SkillASCBreaker: {
		{SkillID: SkillTFDouble, Level: 5},
		{SkillID: SkillTFPoison, Level: 5},
		{SkillID: SkillASCloaking, Level: 3},
		{SkillID: SkillASEnchantpoison, Level: 6},
	},
	SkillASCMeteorassault: {
		{SkillID: SkillASKatar, Level: 5},
		{SkillID: SkillASRight, Level: 3},
		{SkillID: SkillASSonicblow, Level: 5},
		{SkillID: SkillASCBreaker, Level: 1},
	},
	SkillASCCdp: {
		{SkillID: SkillTFPoison, Level: 10},
		{SkillID: SkillTFDetoxify, Level: 1},
		{SkillID: SkillASEnchantpoison, Level: 5},
	},
}

var SkillRequirementsByJob = map[int]map[uint16][]SkillRequirement{
	JobPriest:     priestSkillRequirementOverrides,
	JobPriestH:    priestSkillRequirementOverrides,
	JobPriestB:    priestSkillRequirementOverrides,
	JobCrusader:   crusaderSkillRequirementOverrides,
	JobCrusader2:  crusaderSkillRequirementOverrides,
	JobCrusaderH:  crusaderSkillRequirementOverrides,
	JobCrusader2H: crusaderSkillRequirementOverrides,
	JobCrusaderB:  crusaderSkillRequirementOverrides,
	JobCrusader2B: crusaderSkillRequirementOverrides,
}

var priestSkillRequirementOverrides = map[uint16][]SkillRequirement{
	SkillMGSafetywall: {{SkillID: SkillPRSanctuary, Level: 3}, {SkillID: SkillPRAspersio, Level: 4}},
}

var crusaderSkillRequirementOverrides = map[uint16][]SkillRequirement{
	SkillALCure: {{SkillID: SkillCRTrust, Level: 5}},
	SkillALDp:   {{SkillID: SkillALCure, Level: 1}},
	SkillALHeal: {{SkillID: SkillCRTrust, Level: 10}, {SkillID: SkillALDemonbane, Level: 5}},
}

var SkillMaxLevels = map[uint16]int{
	SkillNVBasic:           9,
	SkillNVFirstaid:        1,
	SkillNVTrickdead:       1,
	SkillSMSword:           10,
	SkillSMTwohand:         10,
	SkillSMRecovery:        10,
	SkillSMBash:            10,
	SkillSMProvoke:         10,
	SkillSMMagnum:          10,
	SkillSMEndure:          10,
	SkillSMMovingrecovery:  1,
	SkillSMFatalblow:       1,
	SkillSMAutoberserk:     1,
	SkillKNSpearmastery:    10,
	SkillKNPierce:          10,
	SkillKNBrandishspear:   10,
	SkillKNSpearstab:       10,
	SkillKNSpearboomerang:  5,
	SkillKNTwohandquicken:  10,
	SkillKNAutocounter:     5,
	SkillKNBowlingbash:     10,
	SkillKNChargeatk:       1,
	SkillKNRiding:          1,
	SkillKNCavaliermastery: 5,
	SkillKNOnehand:         1,
	SkillLKSpiralpierce:    5,
	SkillLKHeadcrush:       5,
	SkillLKJointbeat:       10,
	SkillLKAurablade:       5,
	SkillLKParrying:        10,
	SkillLKConcentration:   5,
	SkillLKTensionrelax:    1,
	SkillLKBerserk:         1,
	SkillCRTrust:           10,
	SkillCRAutoguard:       10,
	SkillCRShieldcharge:    5,
	SkillCRShieldboomerang: 5,
	SkillCRReflectshield:   10,
	SkillCRHolycross:       10,
	SkillCRGrandcross:      10,
	SkillCRDevotion:        5,
	SkillCRProvidence:      5,
	SkillCRDefender:        5,
	SkillCRSpearquicken:    10,
	SkillCRShrink:          1,
	SkillPaPressure:        5,
	SkillPaShieldchain:     5,
	SkillPaSacrifice:       5,
	SkillPaGospel:          10,
	SkillMGSrecovery:       10,
	SkillMGSight:           1,
	SkillMGNapalmbeat:      10,
	SkillMGSafetywall:      10,
	SkillMGSoulstrike:      10,
	SkillMGColdbolt:        10,
	SkillMGFrostdiver:      10,
	SkillMGStonecurse:      10,
	SkillMGFireball:        10,
	SkillMGFirewall:        10,
	SkillMGFirebolt:        10,
	SkillMGLightningbolt:   10,
	SkillMGThunderstorm:    10,
	SkillMGEnergycoat:      1,
	SkillWZFirepillar:      10,
	SkillWZSightrasher:     10,
	SkillWZMeteor:          10,
	SkillWZJupitel:         10,
	SkillWZVermilion:       10,
	SkillWZWaterball:       5,
	SkillWZIcewall:         10,
	SkillWZFrostnova:       10,
	SkillWZStormgust:       10,
	SkillWZEarthspike:      5,
	SkillWZHeavendrive:     5,
	SkillWZQuagmire:        5,
	SkillWZEstimation:      1,
	SkillWZSightblaster:    1,
	SkillHWSouldrain:       10,
	SkillHWMagiccrasher:    1,
	SkillHWMagicpower:      10,
	SkillHWNapalmvulcan:    5,
	SkillHWGanbantein:      1,
	SkillHWGravitation:     5,
	SkillALRuwach:          1,
	SkillALPneuma:          1,
	SkillALTeleport:        2,
	SkillALWarp:            4,
	SkillALHeal:            10,
	SkillALIncagi:          10,
	SkillALDecagi:          10,
	SkillALHolywater:       1,
	SkillALCrucis:          10,
	SkillALAngelus:         10,
	SkillALBlessing:        10,
	SkillALCure:            1,
	SkillALDp:              10,
	SkillALDemonbane:       10,
	SkillALHolylight:       1,
	SkillALLResurrection:   4,
	SkillPRMacemastery:     10,
	SkillPRImpositio:       5,
	SkillPRSuffragium:      3,
	SkillPRAspersio:        5,
	SkillPRBenedictio:      5,
	SkillPRSanctuary:       10,
	SkillPRSlowpoison:      4,
	SkillPRStrecovery:      1,
	SkillPRKyrie:           10,
	SkillPRMagnificat:      5,
	SkillPRGloria:          5,
	SkillPRLexdivina:       10,
	SkillPRTurnundead:      10,
	SkillPRLexaeterna:      1,
	SkillPRMagnus:          10,
	SkillPRRedemptio:       1,
	SkillHPAssumptio:       5,
	SkillHPBasilica:        5,
	SkillHPMeditatio:       10,
	SkillHPManarecharge:    5,
	SkillMCInccarry:        10,
	SkillMCDiscount:        10,
	SkillMCOvercharge:      10,
	SkillMCPushcart:        10,
	SkillMCIdentify:        1,
	SkillMCVending:         10,
	SkillMCMammonite:       10,
	SkillMCCartrevolution:  1,
	SkillMCChangecart:      1,
	SkillMCLoud:            1,
	SkillMCCartdecorate:    1,
	SkillBSIron:            5,
	SkillBSSteel:           5,
	SkillBSEnchantedstone:  5,
	SkillBSOrideocon:       5,
	SkillBSDagger:          3,
	SkillBSSword:           3,
	SkillBSTwohandsword:    3,
	SkillBSAxe:             3,
	SkillBSMace:            3,
	SkillBSKnuckle:         3,
	SkillBSSpear:           3,
	SkillBSHiltbinding:     1,
	SkillBSFindingore:      1,
	SkillBSWeaponresearch:  10,
	SkillBSRepairweapon:    1,
	SkillBSSkintemper:      5,
	SkillBSHammerfall:      5,
	SkillBSAdrenaline:      5,
	SkillBSWeaponperfect:   5,
	SkillBSOverthrust:      5,
	SkillBSMaximize:        5,
	SkillBSAdrenaline2:     1,
	SkillBSUnfairlytrick:   1,
	SkillBSGreed:           1,
	SkillWSMeltdown:        10,
	SkillWSCreatecoin:      3,
	SkillWSCreatenugget:    3,
	SkillWSCartboost:       1,
	SkillWSSystemcreate:    1,
	SkillWSWeaponrefine:    10,
	SkillWSCarttermination: 10,
	SkillWSOverthrustmax:   5,
	SkillACOwl:             10,
	SkillACVulture:         10,
	SkillACConcentration:   10,
	SkillACDouble:          10,
	SkillACShower:          10,
	SkillACMakingarrow:     1,
	SkillACChargearrow:     1,
	SkillHTPower:           1,
	SkillHTPhantasmic:      1,
	SkillHTSkidtrap:        5,
	SkillHTLandmine:        5,
	SkillHTAnklesnare:      5,
	SkillHTShockwave:       5,
	SkillHTSandman:         5,
	SkillHTFlasher:         5,
	SkillHTFreezingtrap:    5,
	SkillHTBlastmine:       5,
	SkillHTClaymoretrap:    5,
	SkillHTRemovetrap:      1,
	SkillHTTalkiebox:       1,
	SkillHTBeastbane:       10,
	SkillHTFalcon:          1,
	SkillHTSteelcrow:       10,
	SkillHTBlitzbeat:       5,
	SkillHTDetecting:       4,
	SkillHTSpringtrap:      5,
	SkillSNSight:           10,
	SkillSNFalconassault:   5,
	SkillSNSharpshooting:   5,
	SkillSNWindwalk:        10,
	SkillTFDouble:          10,
	SkillTFMiss:            10,
	SkillTFSteal:           10,
	SkillTFHiding:          10,
	SkillTFPoison:          10,
	SkillTFDetoxify:        1,
	SkillTFSprinklesand:    1,
	SkillTFBacksliding:     1,
	SkillTFPickstone:       1,
	SkillTFThrowstone:      1,
	SkillASRight:           5,
	SkillASLeft:            5,
	SkillASKatar:           10,
	SkillASCloaking:        10,
	SkillASSonicblow:       10,
	SkillASGrimtooth:       5,
	SkillASEnchantpoison:   10,
	SkillASPoisonreact:     10,
	SkillASVenomdust:       10,
	SkillASSplasher:        10,
	SkillASSonicaccel:      1,
	SkillASVenomknife:      1,
	SkillASCKatar:          5,
	SkillASCEdp:            5,
	SkillASCBreaker:        10,
	SkillASCMeteorassault:  10,
	SkillASCCdp:            1,
}

var superNoviceSkillTree = []uint16{
	SkillSMSword, SkillSMBash, SkillSMProvoke, SkillTFDouble, SkillTFSteal, SkillTFPoison,
	SkillSMRecovery, SkillSMMagnum, SkillSMEndure, SkillTFMiss, SkillTFHiding, SkillTFDetoxify,
	SkillMGStonecurse, SkillMGColdbolt, SkillMGLightningbolt, SkillMGNapalmbeat, SkillMGFirebolt, SkillMGSight,
	SkillMGSrecovery, SkillMGFrostdiver, SkillMGThunderstorm, SkillMGSoulstrike, SkillMGFireball,
	SkillALRuwach, SkillALHeal, SkillALHolywater, SkillALDp, SkillMGSafetywall, SkillMGFirewall,
	SkillACOwl, SkillALTeleport, SkillALCure, SkillALIncagi, SkillALBlessing, SkillALDemonbane, SkillALAngelus,
	SkillACVulture, SkillALWarp, SkillMCInccarry, SkillALDecagi, SkillMCIdentify, SkillALCrucis,
	SkillMCMammonite, SkillACConcentration, SkillALPneuma, SkillMCDiscount, SkillMCOvercharge,
	SkillMCPushcart, SkillMCVending,
}

var magicianSkillTree = []uint16{
	SkillMGStonecurse, SkillMGColdbolt, SkillMGLightningbolt, SkillMGNapalmbeat, SkillMGFirebolt, SkillMGSight, SkillMGSrecovery, SkillMGFrostdiver, SkillMGThunderstorm, SkillMGSoulstrike, SkillMGFireball, SkillMGEnergycoat, SkillMGSafetywall, SkillMGFirewall,
}

var merchantSkillTree = []uint16{
	SkillMCInccarry,
	SkillMCMammonite,
	SkillMCIdentify,
	SkillMCLoud,
	SkillMCDiscount,
	SkillMCPushcart,
	SkillMCChangecart,
	SkillMCCartdecorate,
	SkillMCOvercharge,
	SkillMCVending,
	SkillMCCartrevolution,
}

var blacksmithSkillTree = []uint16{
	SkillBSIron,
	SkillBSHiltbinding,
	SkillBSSkintemper,
	SkillBSHammerfall,
	SkillBSDagger,
	SkillBSSteel,
	SkillBSEnchantedstone,
	SkillBSWeaponresearch,
	SkillBSAdrenaline,
	SkillBSSpear,
	SkillBSSword,
	SkillBSKnuckle,
	SkillBSFindingore,
	SkillBSOrideocon,
	SkillBSRepairweapon,
	SkillBSWeaponperfect,
	SkillBSOverthrust,
	SkillBSTwohandsword,
	SkillBSMace,
	SkillBSMaximize,
	SkillBSAxe,
	SkillBSAdrenaline2,
	SkillBSGreed,
	SkillBSUnfairlytrick,
}

var whitesmithSkillTree = []uint16{
	SkillWSCartboost,
	SkillWSCarttermination,
	SkillWSMeltdown,
	SkillWSOverthrustmax,
	SkillWSWeaponrefine,
}

var archerSkillTree = []uint16{
	SkillACDouble,
	SkillACOwl,
	SkillACChargearrow,
	SkillACShower,
	SkillACVulture,
	SkillACMakingarrow,
	SkillACConcentration,
}

var hunterSkillTree = []uint16{
	SkillHTBeastbane,
	SkillHTSkidtrap,
	SkillHTLandmine,
	SkillHTPower,
	SkillHTFalcon,
	SkillHTFlasher,
	SkillHTAnklesnare,
	SkillHTRemovetrap,
	SkillHTPhantasmic,
	SkillHTBlitzbeat,
	SkillHTSandman,
	SkillHTFreezingtrap,
	SkillHTShockwave,
	SkillHTSpringtrap,
	SkillHTDetecting,
	SkillHTSteelcrow,
	SkillHTBlastmine,
	SkillHTTalkiebox,
	SkillHTClaymoretrap,
}

var sniperSkillTree = []uint16{
	SkillSNFalconassault,
	SkillSNSharpshooting,
	SkillSNSight,
	SkillSNWindwalk,
}

var thiefSkillTree = []uint16{
	SkillTFDouble,
	SkillTFSteal,
	SkillTFPoison,
	SkillTFSprinklesand,
	SkillTFThrowstone,
	SkillTFMiss,
	SkillTFHiding,
	SkillTFDetoxify,
	SkillTFBacksliding,
	SkillTFPickstone,
}

var assassinSkillTree = []uint16{
	SkillASRight,
	SkillASKatar,
	SkillASCloaking,
	SkillASEnchantpoison,
	SkillASVenomknife,
	SkillASLeft,
	SkillASSonicblow,
	SkillASVenomdust,
	SkillASPoisonreact,
	SkillASSonicaccel,
	SkillASGrimtooth,
	SkillASSplasher,
}

var assassinCrossSkillTree = []uint16{
	SkillASCBreaker,
	SkillASCCdp,
	SkillASCEdp,
	SkillASCKatar,
	SkillASCMeteorassault,
}

var acolyteSkillTree = []uint16{
	SkillALRuwach,
	SkillALHeal,
	SkillALHolywater,
	SkillALDp,
	SkillALHolylight,
	SkillALTeleport,
	SkillALCure,
	SkillALIncagi,
	SkillALBlessing,
	SkillALDemonbane,
	SkillALAngelus,
	SkillALWarp,
	SkillALDecagi,
	SkillALCrucis,
	SkillALPneuma,
}

var priestSkillTree = []uint16{
	SkillPRKyrie,
	SkillPRMagnificat,
	SkillPRStrecovery,
	SkillMGSrecovery,
	SkillPRLexdivina,
	SkillPRImpositio,
	SkillPRSanctuary,
	SkillPRGloria,
	SkillPRSlowpoison,
	SkillALLResurrection,
	SkillPRLexaeterna,
	SkillPRSuffragium,
	SkillPRAspersio,
	SkillPRBenedictio,
	SkillPRMacemastery,
	SkillPRTurnundead,
	SkillMGSafetywall,
	SkillPRMagnus,
	SkillPRRedemptio,
}

var highPriestSkillTree = []uint16{
	SkillHPAssumptio,
	SkillHPBasilica,
	SkillHPManarecharge,
	SkillHPMeditatio,
}

var swordmanSkillTree = []uint16{
	SkillSMSword,
	SkillSMRecovery,
	SkillSMBash,
	SkillSMProvoke,
	SkillSMAutoberserk,
	SkillSMMovingrecovery,
	SkillSMTwohand,
	SkillSMMagnum,
	SkillSMEndure,
	SkillSMFatalblow,
}

var knightSkillTree = []uint16{
	SkillKNTwohandquicken,
	SkillKNAutocounter,
	SkillKNRiding,
	SkillKNSpearmastery,
	SkillKNChargeatk,
	SkillKNBowlingbash,
	SkillKNCavaliermastery,
	SkillKNPierce,
	SkillKNOnehand,
	SkillKNSpearboomerang,
	SkillKNSpearstab,
	SkillKNBrandishspear,
}

var lordKnightSkillTree = []uint16{
	SkillLKBerserk,
	SkillLKTensionrelax,
	SkillLKParrying,
	SkillLKAurablade,
	SkillLKConcentration,
	SkillLKHeadcrush,
	SkillLKSpiralpierce,
	SkillLKJointbeat,
}

var crusaderSkillTree = []uint16{
	SkillCRTrust,
	SkillCRAutoguard,
	SkillKNSpearmastery,
	SkillKNRiding,
	SkillCRShrink,
	SkillALCure,
	SkillCRHolycross,
	SkillCRShieldcharge,
	SkillCRSpearquicken,
	SkillKNCavaliermastery,
	SkillALDp,
	SkillCRGrandcross,
	SkillCRShieldboomerang,
	SkillALDemonbane,
	SkillCRReflectshield,
	SkillCRDefender,
	SkillALHeal,
	SkillCRDevotion,
	SkillCRProvidence,
}

var paladinSkillTree = []uint16{
	SkillPaPressure,
	SkillPaShieldchain,
	SkillPaGospel,
	SkillPaSacrifice,
}

var wizardSkillTree = []uint16{
	SkillWZEstimation,
	SkillWZIcewall,
	SkillWZJupitel,
	SkillWZEarthspike,
	SkillWZSightrasher,
	SkillWZFirepillar,
	SkillWZSightblaster,
	SkillWZFrostnova,
	SkillWZVermilion,
	SkillWZHeavendrive,
	SkillWZMeteor,
	SkillWZWaterball,
	SkillWZQuagmire,
	SkillWZStormgust,
}

var highWizardSkillTree = []uint16{
	SkillHWGanbantein,
	SkillHWMagiccrasher,
	SkillHWSouldrain,
	SkillHWNapalmvulcan,
	SkillHWMagicpower,
	SkillHWGravitation,
}

func combinedSkillTree(trees ...[]uint16) []uint16 {
	total := 0
	for _, tree := range trees {
		total += len(tree)
	}
	out := make([]uint16, 0, total)
	for _, tree := range trees {
		out = append(out, tree...)
	}
	return out
}

var skillTreeByJob = map[int][]uint16{
	JobNovice:       {SkillNVBasic, SkillNVFirstaid, SkillNVTrickdead},
	JobSwordman:     swordmanSkillTree,
	JobSwordmanH:    swordmanSkillTree,
	JobSwordmanB:    swordmanSkillTree,
	JobKnight:       combinedSkillTree(swordmanSkillTree, knightSkillTree),
	JobKnight2:      combinedSkillTree(swordmanSkillTree, knightSkillTree),
	JobKnightH:      combinedSkillTree(swordmanSkillTree, knightSkillTree, lordKnightSkillTree),
	JobKnight2H:     combinedSkillTree(swordmanSkillTree, knightSkillTree, lordKnightSkillTree),
	JobKnightB:      combinedSkillTree(swordmanSkillTree, knightSkillTree),
	JobKnight2B:     combinedSkillTree(swordmanSkillTree, knightSkillTree),
	JobCrusader:     combinedSkillTree(swordmanSkillTree, crusaderSkillTree),
	JobCrusader2:    combinedSkillTree(swordmanSkillTree, crusaderSkillTree),
	JobCrusaderH:    combinedSkillTree(swordmanSkillTree, crusaderSkillTree, paladinSkillTree),
	JobCrusader2H:   combinedSkillTree(swordmanSkillTree, crusaderSkillTree, paladinSkillTree),
	JobCrusaderB:    combinedSkillTree(swordmanSkillTree, crusaderSkillTree),
	JobCrusader2B:   combinedSkillTree(swordmanSkillTree, crusaderSkillTree),
	JobMagician:     magicianSkillTree,
	JobMagicianH:    magicianSkillTree,
	JobMagicianB:    magicianSkillTree,
	JobWizard:       combinedSkillTree(magicianSkillTree, wizardSkillTree),
	JobWizardH:      combinedSkillTree(magicianSkillTree, wizardSkillTree, highWizardSkillTree),
	JobWizardB:      combinedSkillTree(magicianSkillTree, wizardSkillTree),
	JobArcher:       archerSkillTree,
	JobArcherH:      archerSkillTree,
	JobArcherB:      archerSkillTree,
	JobHunter:       combinedSkillTree(archerSkillTree, hunterSkillTree),
	JobHunterH:      combinedSkillTree(archerSkillTree, hunterSkillTree, sniperSkillTree),
	JobHunterB:      combinedSkillTree(archerSkillTree, hunterSkillTree),
	JobAcolyte:      acolyteSkillTree,
	JobAcolyteH:     acolyteSkillTree,
	JobAcolyteB:     acolyteSkillTree,
	JobPriest:       combinedSkillTree(acolyteSkillTree, priestSkillTree),
	JobPriestH:      combinedSkillTree(acolyteSkillTree, priestSkillTree, highPriestSkillTree),
	JobPriestB:      combinedSkillTree(acolyteSkillTree, priestSkillTree),
	JobMerchant:     merchantSkillTree,
	JobMerchantH:    merchantSkillTree,
	JobMerchantB:    merchantSkillTree,
	JobBlacksmith:   combinedSkillTree(merchantSkillTree, blacksmithSkillTree),
	JobBlacksmithH:  combinedSkillTree(merchantSkillTree, blacksmithSkillTree, whitesmithSkillTree),
	JobBlacksmithB:  combinedSkillTree(merchantSkillTree, blacksmithSkillTree),
	JobThief:        thiefSkillTree,
	JobThiefH:       thiefSkillTree,
	JobThiefB:       thiefSkillTree,
	JobAssassin:     combinedSkillTree(thiefSkillTree, assassinSkillTree),
	JobAssassinH:    combinedSkillTree(thiefSkillTree, assassinSkillTree, assassinCrossSkillTree),
	JobAssassinB:    combinedSkillTree(thiefSkillTree, assassinSkillTree),
	JobSuperNovice:  superNoviceSkillTree,
	JobSuperNoviceB: superNoviceSkillTree,
}

func SkillTreeSkillIDs(job int) []uint16 {
	out := append([]uint16(nil), skillTreeByJob[JobNovice]...)
	if job != JobNovice {
		out = append(out, skillTreeByJob[job]...)
	}
	return out
}

func SkillMaxLevel(skillID uint16) (int, bool) {
	level, ok := SkillMaxLevels[skillID]
	return level, ok && level > 0
}

func SkillRequirementsForJob(job int, skillID uint16) []SkillRequirement {
	if bySkill, ok := SkillRequirementsByJob[job]; ok {
		if requirements, ok := bySkill[skillID]; ok {
			return requirements
		}
	}
	return SkillRequirements[skillID]
}
