package db

// skillSelectableLevels mirrors the reference client's bSeperateLv=true
// metadata for every skill in Goro's pre-renewal player skill trees. Skills
// present in SkillMaxLevels but absent here are known fixed-level skills.
var skillSelectableLevels = map[uint16]struct{}{
	SkillSMBash:            {},
	SkillSMProvoke:         {},
	SkillKNSpearstab:       {},
	SkillKNTwohandquicken:  {},
	SkillKNBowlingbash:     {},
	SkillLKSpiralpierce:    {},
	SkillLKJointbeat:       {},
	SkillLKAurablade:       {},
	SkillLKParrying:        {},
	SkillLKConcentration:   {},
	SkillCRAutoguard:       {},
	SkillCRReflectshield:   {},
	SkillCRHolycross:       {},
	SkillCRGrandcross:      {},
	SkillCRSpearquicken:    {},
	SkillPaPressure:        {},
	SkillPaShieldchain:     {},
	SkillPaGospel:          {},
	SkillMGSafetywall:      {},
	SkillMGSoulstrike:      {},
	SkillMGColdbolt:        {},
	SkillMGFirebolt:        {},
	SkillMGLightningbolt:   {},
	SkillMGThunderstorm:    {},
	SkillWZFirepillar:      {},
	SkillWZSightrasher:     {},
	SkillWZMeteor:          {},
	SkillWZJupitel:         {},
	SkillWZVermilion:       {},
	SkillWZWaterball:       {},
	SkillWZStormgust:       {},
	SkillWZEarthspike:      {},
	SkillWZHeavendrive:     {},
	SkillHWMagicpower:      {},
	SkillHWNapalmvulcan:    {},
	SkillHWGravitation:     {},
	SkillPFSoulburn:        {},
	SkillPFMindbreaker:     {},
	SkillALTeleport:        {},
	SkillALHeal:            {},
	SkillALIncagi:          {},
	SkillALDecagi:          {},
	SkillALAngelus:         {},
	SkillALBlessing:        {},
	SkillPRImpositio:       {},
	SkillPRSuffragium:      {},
	SkillPRAspersio:        {},
	SkillPRSanctuary:       {},
	SkillPRSlowpoison:      {},
	SkillPRKyrie:           {},
	SkillPRMagnus:          {},
	SkillHPAssumptio:       {},
	SkillHPBasilica:        {},
	SkillMOInvestigate:     {},
	SkillMOFingeroffensive: {},
	SkillMOChaincombo:      {},
	SkillMOCombofinish:     {},
	SkillChPalmstrike:      {},
	SkillChTigerfist:       {},
	SkillChChaincrush:      {},
	SkillMCMammonite:       {},
	SkillBSAdrenaline:      {},
	SkillBSOverthrust:      {},
	SkillWSMeltdown:        {},
	SkillACConcentration:   {},
	SkillHTSkidtrap:        {},
	SkillHTLandmine:        {},
	SkillHTAnklesnare:      {},
	SkillHTShockwave:       {},
	SkillHTSandman:         {},
	SkillHTFlasher:         {},
	SkillHTFreezingtrap:    {},
	SkillHTBlastmine:       {},
	SkillHTClaymoretrap:    {},
	SkillHTBlitzbeat:       {},
	SkillSNSight:           {},
	SkillSNFalconassault:   {},
	SkillSNSharpshooting:   {},
	SkillSNWindwalk:        {},
	SkillTFHiding:          {},
	SkillRGStripweapon:     {},
	SkillRGStripshield:     {},
	SkillRGStriparmor:      {},
	SkillRGStriphelm:       {},
	SkillRGIntimidate:      {},
	SkillSTRejectsword:     {},
	SkillSTFullstrip:       {},
	SkillASSonicblow:       {},
	SkillASSplasher:        {},
	SkillASCEdp:            {},
	SkillASCBreaker:        {},
	SkillASCMeteorassault:  {},
	SkillAMPotionpitcher:   {},
	SkillAMCannibalize:     {},
	SkillAMResurrecthomun:  {},
	SkillCRSlimpitcher:     {},
	SkillCRCultivation:     {},
	SkillBDDrumbattlefield: {},
	SkillBDRingnibelungen:  {},
	SkillBaMusicalstrike:   {},
	SkillBaDissonance:      {},
	SkillBaFrostjoke:       {},
	SkillBaWhistle:         {},
	SkillBaAssassincross:   {},
	SkillBaPoembragi:       {},
	SkillBaAppleidun:       {},
	SkillDCThrowarrow:      {},
	SkillDCUglydance:       {},
	SkillDCScream:          {},
	SkillDCHumming:         {},
	SkillDCDontforgetme:    {},
	SkillDCFortunekiss:     {},
	SkillDCServiceforyou:   {},
	SkillCGArrowvulcan:     {},
	SkillCGMoonlit:         {},
}

func SkillLevelSelectable(skillID uint16) (bool, bool) {
	if _, selectable := skillSelectableLevels[skillID]; selectable {
		return true, true
	}
	_, known := SkillMaxLevel(skillID)
	return false, known
}

// SkillAttackRanges mirrors roBrowser's DB/Skills/SkillInfo.js AttackRange rows.
// It is intentionally sparse so broader SkillInfo metadata can be batch-imported later.
var SkillAttackRanges = map[uint16][]int{
	SkillWEMale:             {9},
	SkillWEFemale:           {9},
	SkillWECallpartner:      {1},
	SkillWEBaby:             {9},
	SkillWECallparent:       {1},
	SkillWECallbaby:         {1},
	SkillHlifHeal:           {1, 1, 1, 1, 1},
	SkillHlifAvoid:          {1, 1, 1, 1, 1},
	SkillHlifBrain:          {1, 1, 1, 1, 1},
	SkillHlifChange:         {1, 1, 1},
	SkillHamiCastle:         {1, 1, 1, 1, 1},
	SkillHamiDefence:        {1, 1, 1, 1, 1},
	SkillHamiSkin:           {1, 1, 1, 1, 1},
	SkillHamiBloodlust:      {1, 1, 1},
	SkillHfliMoon:           {1, 1, 1, 1, 1},
	SkillHfliFleet:          {1, 1, 1, 1, 1},
	SkillHfliSpeed:          {1, 1, 1, 1, 1},
	SkillHfliSbr44:          {9, 9, 9},
	SkillHvanCaprice:        {9, 9, 9, 9, 9},
	SkillHvanChaotic:        {1, 1, 1, 1, 1},
	SkillHvanInstruct:       {1, 1, 1, 1, 1},
	SkillHvanExplosion:      {1, 1, 1},
	SkillMhSummonLegion:     {9, 9, 9, 9, 9},
	SkillMhNeedleOfParalyze: {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMhPoisonMist:       {5, 5, 5, 5, 5},
	SkillMhPainKiller:       {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMhLightOfRegene:    {1, 1, 1, 1, 1},
	SkillMhOveredBoost:      {1, 1, 1, 1, 1},
	SkillMhEraserCutter:     {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhXenoSlasher:      {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhSilentBreeze:     {5, 5, 7, 7, 9},
	SkillMhStyleChange:      {1},
	SkillMhSonicCraw:        {1, 1, 1, 1, 1},
	SkillMhSilverveinRush:   {3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
	SkillMhMidnightFrenzy:   {3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
	SkillMhStahlHorn:        {5, 5, 6, 6, 7, 7, 8, 8, 9, 9},
	SkillMhGoldeneFerse:     {1, 1, 1, 1, 1},
	SkillMhSteinwand:        {1, 1, 1, 1, 1},
	SkillMhHeiligeStange:    {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMhAngriffsModus:    {1, 1, 1, 1, 1},
	SkillMhTinderBreaker:    {3, 4, 5, 6, 7},
	SkillMhCbc:              {1, 1, 1, 1, 1},
	SkillMhEqc:              {1, 1, 1, 1, 1},
	SkillMhMagmaFlow:        {1, 1, 1, 1, 1},
	SkillMhGraniticArmor:    {1, 1, 1, 1, 1},
	SkillMhLavaSlide:        {7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
	SkillMhPyroclastic:      {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMhVolcanicAsh:      {7, 7, 7, 7, 7},
	SkillMsBash:             {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsMagnum:           {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsBowlingbash:      {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMsParrying:         {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsReflectshield:    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMsBerserk:          {1},
	SkillMaDouble:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMaShower:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMaSkidtrap:         {3, 3, 3, 3, 3},
	SkillMaLandmine:         {3, 3, 3, 3, 3},
	SkillMaSandman:          {3, 3, 3, 3, 3},
	SkillMaFreezingtrap:     {3, 3, 3, 3, 3},
	SkillMaRemovetrap:       {2},
	SkillMaChargearrow:      {9},
	SkillMaSharpshooting:    {9, 9, 9, 9, 9},
	SkillMlPierce:           {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMlBrandish:         {2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
	SkillMlSpiralpierce:     {4, 4, 4, 4, 4},
	SkillMlDefender:         {1, 1, 1, 1, 1},
	SkillMlAutoguard:        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMlDevotion:         {7, 8, 9, 10, 11},
	SkillMerMagnificat:      {1, 1, 1, 1, 1},
	SkillMerQuicken:         {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
	SkillMerSight:           {1},
	SkillMerCrash:           {1, 1, 1, 1, 1},
	SkillMerRegain:          {9},
	SkillMerTender:          {9},
	SkillMerBenediction:     {9},
	SkillMerRecuperate:      {9},
	SkillMerMentalcure:      {9},
	SkillMerCompress:        {9},
	SkillMerProvoke:         {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerAutoberserk:     {1},
	SkillMerDecagi:          {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerScapegoat:       {1},
	SkillMerLexdivina:       {5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
	SkillMerEstimation:      {9},
	SkillMerKyrie:           {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerBlessing:        {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerIncagi:          {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
	SkillMerInvincibleoff2:  {2},
}

func SkillAttackRange(skillID uint16, level int) (int, bool) {
	ranges, ok := SkillAttackRanges[skillID]
	if !ok || level <= 0 || level > len(ranges) {
		return 0, false
	}
	return ranges[level-1], true
}
